---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: cs-alert-worker
  namespace: xpp
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: glob:*-xps93441.*
spec:
  releaseName: cs-alert-worker
  targetNamespace: integration
  forceUpgrade: false
  chart:
    repository: https://na.artifactory.swg-devops.com/artifactory/mss-helm-virtual
    name: cs-alert-worker
    version: 1.4.14-xps93441
  values:
    replicaCount: 2
    revisionHistoryLimit: 1
    image:
      repository: mss-docker.artifactory.swg-devops.com/cs-alert-worker
      tag: 1.4.14-xps93441.5ce43941
    graphite:
      enabled: false
      host: dal09-prd-statsnode-01a.sec.ibm.com
      prefix: dev.k8s.integration
    secretName: cs-alert-worker
    config:
      mdr:
        retryAttempts: 3
        retryBackoffSeconds: 30
        skipAlertUpdateTrigger: "[skip alert-update]"
        services:
          baseUrl: https://dal09-dev-services.sec.ibm.com
          timeoutSeconds: 15
        worklog:
          retryAttempts: 3
          retryBackoffSeconds: 30
      spring:
        kafka:
          bootstrap-servers: dal09-dev-kfk-01a.sec.ibm.com:9093,dal09-dev-kfk-01b.sec.ibm.com:9093,dal09-dev-kfk-01c.sec.ibm.com:9093
    env:
      DOCKER_REGISTRY_PULL_SECRET_NAME: docker-registry-pull
      LOG_FORMAT: json
      LOG_LEVEL: DEBUG
