---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: mdr-cs-puma-drone
  namespace: xpp
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: glob:*master*
spec:
  releaseName: mdr-cs-puma-drone
  forceUpgrade: true
  chart:
    git: git@github.ibm.com:managed-security/mdr-cs-puma-drone
    ref: master
    path: mdr-cs-puma-drone
  values:
    devices:
    # - PR0000000028525
    image:
      repository: mss-docker.artifactory.swg-devops.com/mdr-cs-puma-drone
      tag: master-a3f612d3
    secretName: "mdr-cs-puma-drone"
    testSyslogServer:
      enabled: false
      name: mdr-cs-puma-drone-syslog
    env:
      DOCKER_REGISTRY_PULL_SECRET_NAME: docker-registry-pull
      SERVICES_BASE_URL: dal09-dev-services.sec.ibm.com
      SYSLOG_SERVER_IP: dal09-dev-agg-01a.sec.ibm.com
      SYSLOG_SERVER_PORT: 514
      FIELD_DELIM: "|"
