---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: token-ms
  namespace: xpp
  annotations:
    fluxcd.io/automated: "false"
    filter.fluxcd.io/chart-image: glob:*-master.*
spec:
  releaseName: token-ms
  forceUpgrade: true
  chart:
    repository: https://na.artifactory.swg-devops.com/artifactory/mss-helm-virtual
    name: token-ms
    version: 1.0.6-master
  values:
    service:
      targetPort: 3333
    readinessProbe:
      initialDelaySeconds: 30
    livenessProbe:
      initialDelaySeconds: 30
    image:
      repository: mss-docker.artifactory.swg-devops.com/token-ms
      tag: 1.0.6-master.5dd0a9a1
    graphite:
      enabled: true
      host: ruh01-prd-statsnode-01a.sec.ibm.com
      prefix: prd.k8s.xpp
    secretName: token-ms
    ingress:
      enabled: true
      hosts:
        - host: token-ms.ruh01-prd.k8s.sec.ibm.com
          paths:
          - /
      tls:
        - hosts:
            - token-ms.ruh01-prd.k8s.sec.ibm.com
          secretName: token-ms
    config:
      server:
        port: 3333
      token-ms:
        mss-datasource:
          jdbc-url: jdbc:mysql://ruh01-prd-mssdb-01a.sec.ibm.com:3306/mss
    env:
      LOG_FORMAT: plain
      LOG_LEVEL: DEBUG
