---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: mdatp-response-worker
  namespace: xpp
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: mdatp-response-worker
  chart:
    git: git@github.ibm.com:managed-security/mdatp-response-worker
    ref: v1.0.2
    path: chart
  values:
    log:
      level: DEBUG
    image:
      repository: mss-docker.artifactory.swg-devops.com/mdatp-response-worker
      tag: 1.0.2
    graphite:
      enabled: true
      host: dal09-prd-statsnode-01a.sec.ibm.com
      prefix: stg.k8s.xpp
    secretName: mdatp-response-worker
    config:
      mdr:
        services:
          baseUrl: https://stg-services.sec.ibm.com
          timeoutSeconds: 30
      spring:
        kafka:
          bootstrap-servers: atl-stg-kfk-01a.sec.ibm.com:9093, atl-stg-kfk-01b.sec.ibm.com:9093,atl-stg-kfk-01c.sec.ibm.com:9093
