---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: mdr-report
  namespace: xpp
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: glob:*-master.*
spec:
  releaseName: mdr-report
  forceUpgrade: true
  chart:
    git: git@github.ibm.com:managed-security/mdr-report
    ref: master
    path: chart
  values:
    replicaCount: 1
    revisionHistoryLimit: 1
    image:
      repository: mss-docker.artifactory.swg-devops.com/mdr-report
      tag: 0.0.16-master.69814ad8
    graphite:
      enabled: true
      host: dal09-prd-statsnode-01a.sec.ibm.com
      prefix: stg.k8s.xpp
    secretName: mdr-report
    config:
      mdr:
        retry:
          maxAttempts: 3
          delay: 3000
        attachmentDescription: General
        services:
          baseUrl: https://stg-services.sec.ibm.com
          timeoutSeconds: 60
      spring:
        kafka:
          bootstrap-servers: atl-stg-kfk-01a.sec.ibm.com:9093, atl-stg-kfk-01b.sec.ibm.com:9093,
            atl-stg-kfk-01c.sec.ibm.com:9093
    env:
      DOCKER_REGISTRY_PULL_SECRET_NAME: docker-registry-pull
      LOG_FORMAT: json
      LOG_LEVEL: DEBUG
