---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: mdr-kafka-craftbench
  namespace: xpp
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: glob:*-master.*
spec:
  releaseName: mdr-kafka-craftbench
  forceUpgrade: true
  chart:
    git: git@github.ibm.com:managed-security/mdr-kafka-craftbench
    ref: master
    path: mdr-kafka-craftbench
  values:
    replicaCount: 1
    revisionHistoryLimit: 1
    image:
      repository: mss-docker.artifactory.swg-devops.com/mdr-kafka-craftbench
      tag: 0.0.1-master.ee70be12
    secretName: mdr-kafka-craftbench
    ingress:
      enabled: true
      host: atl-stg.k8s.sec.ibm.com
      secretName: ingress-wildcard-cert
    config:
      spring:
        kafka:
          bootstrap-servers: atl-stg-kfk-01a.sec.ibm.com:9093,atl-stg-kfk-01b.sec.ibm.com:9093,atl-stg-kfk-01c.sec.ibm.com:9093
      log-feed:
        destinationIp: atl-stg-agg-01b.sec.ibm.com
