---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: response-request-listener
  namespace: xpp
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: response-request-listener
  chart:
    git: git@github.ibm.com:managed-security/response-request-listener
    ref: v1.1.4
    path: chart
  values:
    log:
      level: DEBUG
    image:
      repository: mss-docker.artifactory.swg-devops.com/response-request-listener
      tag: 1.1.4
    graphite:
      enabled: true
      host: dal09-prd-statsnode-01a.sec.ibm.com
      prefix: stg.k8s.xpp
    secretName: response-request-listener
    config:
      mdr:
        services:
          baseUrl: https://stg-services.sec.ibm.com
          timeoutSeconds: 15
        resilient:
          broker-url: ssl://atl-dev-resdemo-01a.sec.ibm.com:65000
          org-id: 204
          queue: "actions.204.auto_response"
      spring:
        kafka:
          bootstrap-servers: atl-stg-kfk-01a.sec.ibm.com:9093, atl-stg-kfk-01b.sec.ibm.com:9093,atl-stg-kfk-01c.sec.ibm.com:9093
