---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: ticket-status-update-worker
  namespace: xpp
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: glob:*-master*
spec:
  releaseName: ticket-status-update-worker
  chart:
    repository: https://na.artifactory.swg-devops.com/artifactory/mss-helm-virtual
    name: ticket-status-update-worker
    version: 0.0.1-master
  values:
    log:
      level: DEBUG
    image:
      repository: mss-docker.artifactory.swg-devops.com/ticket-status-update-worker
      tag: 0.0.1-master.5469f53b
    graphite:
      enabled: true
      host: dal09-prd-statsnode-01a.sec.ibm.com
      prefix: stg.k8s.xpp
    secretName: ticket-status-update-worker
    config:
      mdr:
        services:
          baseUrl: https://stg-services.sec.ibm.com
          timeoutSeconds: 15
      spring:
        kafka:
          bootstrap-servers: atl-stg-kfk-01a.sec.ibm.com:9093, atl-stg-kfk-01b.sec.ibm.com:9093,atl-stg-kfk-01c.sec.ibm.com:9093
