---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: security-stream-redeem
  namespace: xpp
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: glob:*-dev.*
spec:
  targetNamespace: horizon
  releaseName: security-stream-redeem
  chart:
    git: git@github.ibm.com:managed-security/security-stream-redeem
    ref: dev
    path: chart
  values:
    service:
      port: 3000
    image:
      repository: mss-docker.artifactory.swg-devops.com/security-stream-redeem
      tag: 1.2.1-dev.d14e5903
    log:
      level: "debug"
    config:
      PORT: 3000
    serviceAccount:
      create: true
    secretsDir: "/vault/secrets"
    podAnnotations:
      vault.hashicorp.com/agent-inject: "true"
      vault.hashicorp.com/role: "security-stream-redeem"
      vault.hashicorp.com/agent-inject-secret-intra_access_key: "secret/data/modules/security-stream-redeem/auth"
      vault.hashicorp.com/agent-inject-template-intra_access_key: |-
        {{- with secret "secret/data/modules/security-stream-redeem/auth" -}}{{- .Data.data.INTRA_ACCESS_KEY -}}{{- end }}
      vault.hashicorp.com/agent-inject-secret-cloudant_url: "secret/data/modules/security-stream-redeem/cloudant/global"
      vault.hashicorp.com/agent-inject-template-cloudant_url: |-
        {{- with secret "secret/data/modules/security-stream-redeem/cloudant/global" -}}{{- .Data.data.CLOUDANT_URL -}}{{- end }}
      vault.hashicorp.com/agent-inject-secret-stream_seed: "secret/data/modules/security-stream-redeem/cloudant/global"
      vault.hashicorp.com/agent-inject-template-stream_seed: |-
        {{- with secret "secret/data/modules/security-stream-redeem/cloudant/global" -}}{{- .Data.data.STREAM_SEED -}}{{- end }}
