---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: tmx-web-ui
  namespace: xpp
  annotations:
    fluxcd.io/automated: 'false'
    filter.fluxcd.io/chart-image: semver:1.0.28
spec:
  releaseName: tmx-web-ui
  chart:
    repository: https://na.artifactory.swg-devops.com/artifactory/mss-helm-virtual
    version: 1.0.28
    name: glass-webui
  values:
    image:
      repository: mss-docker.artifactory.swg-devops.com/glass-webui
      tag: 1.0.28
    imagePullSecrets:
    - name: xpp-docker-registry-pull 
    env:
      DOCKER_REGISTRY_PULL_SECRET_NAME: docker-registry-pull
      SERVER: https://glass-backend-xpp.atl-prd.k8s.sec.ibm.com
      NEXTAUTH_URL: https://glass.sec.ibm.com
      MSS_API: https://services.sec.ibm.com
      PIWIK_SERVER: https://piwik.sec.ibm.com
      PIWIK_SITE_ID: 29
      PIWIK_CONTAINER_ID: zS8WRUiG
      NEW_RELIC_APP_NAME: Glass-UI-stg
    ingress:
      host: atl-prd.k8s.sec.ibm.com
      appDnsAlias: glass.sec.ibm.com
