---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: glass-backend
  namespace: xpp
  annotations:
    fluxcd.io/automated: 'false'
    filter.fluxcd.io/chart-image: semver:1.0.26
spec:
  releaseName: glass-backend-flux
  chart:
    repository: https://na.artifactory.swg-devops.com/artifactory/mss-helm-virtual
    version: 1.0.26
    name: glass-backend
  values:
    image:
      repository: mss-docker.artifactory.swg-devops.com/glass-backend
      tag: 1.0.26
    imagePullSecrets:
    - name: xpp-docker-registry-pull
    env:
      DOCKER_REGISTRY_PULL_SECRET_NAME: docker-registry-pull
      SERVICES_BASE_URL: https://services.sec.ibm.com
      NODE_ENV: production
      HOURS_BACK: 24
      TOKEN_TYPE: SessionToken
      GLASS_CASE_MS_BASE_URL: https://glass-cases-ms-xpp.atl-prd.k8s.sec.ibm.com
      WTDS_SERVICE_URL: http://atl-stg-lmsrp-01a.sec.ibm.com:8000
    ingress:
      host: atl-prd.k8s.sec.ibm.com
