---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: kwdemo1
  namespace: xpp
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: glob:*-master.*
spec:
  releaseName: kwdemo1
  forceUpgrade: true
  chart:
    repository: https://na.artifactory.swg-devops.com/artifactory/mss-helm-virtual
    name: kwdemo1
    version: 1.0.0-master
  values:
    image:
      repository: mss-docker.artifactory.swg-devops.com/kwdemo1
      tag: 1.0.0-master.237a5733
    imagePullSecrets:
    - name: xpp-docker-registry-pull
    graphite:
      enabled: true
      host: atl-prd-statsnode-01a.sec.ibm.com
      prefix: lab.ocp.xpp
    # TEMPLATE: Insert other required configuration values here
