---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: azure-loganalytics-query
  namespace: xpp
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: glob:*-integration.*
spec:
  releaseName: azure-loganalytics-query
  forceUpgrade: true
  chart:
    git: git@github.ibm.com:managed-security/azure-loganalytics-query
    ref: integration
    path: chart
  values:
    replicaCount: 1
    revisionHistoryLimit: 1
    image:
      repository: mss-docker.artifactory.swg-devops.com/azure-loganalytics-query
      tag: 0.0.11-integration.e436826a
    graphite:
      enabled: false
      host: dal09-prd-statsnode-01a.sec.ibm.com
      prefix: stg.k8s.integration
    route:
      enabled: false
    ingress:
      enabled: true
      hosts:
      - host: azure-loganalytics-query.atl-stg.k8s.sec.ibm.com
        paths:
        - /
      tls:
      - hosts:
        - azure-loganalytics-query.atl-stg.k8s.sec.ibm.com
    config:
      app:
        services:
          timeoutSeconds: 60
    secretsDir: "/vault/secrets"
    serviceAccount:
      create: true
    podAnnotations:
      vault.hashicorp.com/agent-inject: "true"
      vault.hashicorp.com/role: "azure-loganalytics-query"
      vault.hashicorp.com/agent-inject-secret-app.services.admin-token: "secret/data/modules/azure-loganalytics-query/client/services/auth"
      vault.hashicorp.com/agent-inject-template-app.services.admin-token: |-
        {{- with secret "secret/data/modules/azure-loganalytics-query/client/services/auth" -}}{{- .Data.data.TOKEN -}}{{- end }}
    env:
      DOCKER_REGISTRY_PULL_SECRET_NAME: docker-registry-pull
      LOG_FORMAT: json
      LOG_LEVEL: DEBUG
