---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: glass-cases-ms
  namespace: xpp
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: glob:*-rc.*
spec:
  releaseName: glass-cases-flux
  forceUpgrade: true
  chart:
    git: git@github.ibm.com:managed-security/glass-cases-ms
    ref: master
    path: glass-cases-ms
  values:
    image:
      repository: mss-docker.artifactory.swg-devops.com/managed-security/glass-cases-ms
      tag: 1.1.1-rc.41-1461f3ba
    env:
      DOCKER_REGISTRY_PULL_SECRET_NAME: docker-registry-pull
      MSS_API: https:/stg-services.sec.ibm.com
      LOG_FORMAT: plain
      LOG_LEVEL: info
      DB_POOL_MAX: 100
      PUBLIC_URL: https://glass-cases-ms-xpp.atl-stg.k8s.sec.ibm.com
    ingress:
      host: atl-stg.k8s.sec.ibm.com
