---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: internet-emergency-ms
  namespace: xpp
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: glob:*-stg.*
spec:
  releaseName: internet-emergency-ms
  forceUpgrade: true
  chart:
    repository: https://na.artifactory.swg-devops.com/artifactory/mss-helm-virtual
    name: internet-emergency-ms
    version: 1.0.1-master
  values:
    service:
      targetPort: 3333
    readinessProbe:
      initialDelaySeconds: 30
    livenessProbe:
      initialDelaySeconds: 30
    image:
      repository: mss-docker.artifactory.swg-devops.com/internet-emergency-ms
      tag: 1.0.1-master.612d2d1d
    graphite:
      enabled: true
      host: dal09-prd-statsnode-01a.sec.ibm.com
      prefix: stg.k8s.xpp
    secretName: internet-emergency-ms
    ingress:
      enabled: true
      hosts:
        - host: internet-emergency-ms.atl-stg.k8s.sec.ibm.com
          paths:
            - /
      tls:
        - hosts:
            - internet-emergency-ms.atl-stg.k8s.sec.ibm.com
          secretName: internet-emergency-ms
    config:
      server:
        port: 3333
      app:
        elasticSearch:
          baseUrl: atl-stg-eas-01a.sec.ibm.com:9200,atl-stg-eas-01b.sec.ibm.com:9200,atl-stg-eas-01c.sec.ibm.com:9200
          indexName: opsinternetemergency
          type: internetemergency
    env:
      LOG_FORMAT: plain
      LOG_LEVEL: DEBUG
