---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: mars-sentinel-incident-collector
  namespace: xpp
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: glob:*-master.*
spec:
  releaseName: mars-sentinel-incident-collector
  forceUpgrade: true
  chart:
    git: git@github.ibm.com:managed-security/mars-sentinel-incident-collector
    ref: v1.0.4
    path: chart
  values:
    replicaCount: 1
    revisionHistoryLimit: 1
    image:
      repository: mss-docker.artifactory.swg-devops.com/mars-sentinel-incident-collector
      tag: 1.0.4-master.ff7f0294
    secretName: mars-sentinel-incident-collector
    imagePullSecrets:
    - name: docker-registry-pull
    graphite:
      enabled: false
      host: dal09-prd-statsnode-01a.sec.ibm.com
      prefix: stg.k8s.master
    env:
      DOCKER_REGISTRY_PULL_SECRET_NAME: docker-registry-pull
      LOG_FORMAT: json
      LOG_LEVEL: DEBUG
      NEW_RELIC_LOG_FILE_NAME: STDOUT
      NEW_RELIC_LOG_LEVEL: WARN
      NEW_RELIC_SYNC_STARTUP: true
      NEW_RELIC_AGENT_ENABLED: true
      NEW_RELIC_SEND_DATA_ON_EXIT: true
      NEW_RELIC_SEND_DATA_ON_EXIT_THRESHOLD: 60
      NEW_RELIC_APP_NAME: mars-sentinel-incident-collector-stg
      NEW_RELIC_LABELS: Application:Mars-sentinel-incident-collector;Org:Lhs;Region:Atl;Stack:Stg;Namespace:Integration
    config:
      app:
        services:
          baseUrl: https://stg-services.sec.ibm.com
          timeoutSeconds: 30
      spring:
        kafka:
          bootstrap-servers: atl-stg-kfk-01a.sec.ibm.com:9093,atl-stg-kfk-01b.sec.ibm.com:9093,atl-stg-kfk-01c.sec.ibm.com:9093
