---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: mars_test_request_builder_ms
  namespace: xpp
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: glob:*-master.*
spec:
  releaseName: mars_test_request_builder_ms
  forceUpgrade: true
  chart:
    repository: https://na.artifactory.swg-devops.com/artifactory/mss-helm-virtual
    name: mars_test_request_builder_ms
    version: 0.0.1-master
  values:
    replicaCount: 1
    revisionHistoryLimit: 1
    image:
      repository: mss-docker.artifactory.swg-devops.com/mars_test_request_builder_ms
      tag: 0.0.1-master.f68895cb
    graphite:
      enabled: true
      host: dal09-prd-statsnode-01a.sec.ibm.com
      prefix: stg.k8s.xpp
    imagePullSecrets:
      - name: docker-registry-pull
    env:
      LOG_FORMAT: json
      LOG_LEVEL: DEBUG
