---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: snow-update-listener
  namespace: xpp
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: glob:*-master.*
spec:
  releaseName: snow-update-listener
  forceUpgrade: true
  chart:
    repository: https://na.artifactory.swg-devops.com/artifactory/mss-helm-virtual
    name: snow-update-listener
    version: 1.0.5-master
  values:
    service:
      targetPort: 3333
    readinessProbe:
      initialDelaySeconds: 30
    livenessProbe:
      initialDelaySeconds: 30
    image:
      repository: mss-docker.artifactory.swg-devops.com/snow-update-listener
      tag: 1.0.5-master.03480fe9
    graphite:
      enabled: true
      host: dal09-prd-statsnode-01a.sec.ibm.com
      prefix: stg.k8s.master
    secretName: snow-update-listener
    ingress:
      enabled: true
      hosts:
      - host: snow-update-listener.atl-stg.k8s.sec.ibm.com
        paths:
        - /
      tls:
      - hosts:
        - snow-update-listener.atl-stg.k8s.sec.ibm.com
        secretName: snow-update-listener
    config:
      server:
        port: 3333
      app:
        elasticSearch:
          baseUrl: atl-stg-eas-01a.sec.ibm.com:9200,atl-stg-eas-01b.sec.ibm.com:9200,atl-stg-eas-01c.sec.ibm.com:9200
          indexName: servicenow
          type: incident
        serviceNow:
          scheme: https
          baseUrl: secsupportstg.service-now.com
          endpoint: "/api/now/table/{schema}/{id}"
      spring:
        kafka:
          bootstrap-servers: atl-stg-kfk-01a.sec.ibm.com:9093,atl-stg-kfk-01b.sec.ibm.com:9093,atl-stg-kfk-01c.sec.ibm.com:9093
    env:
      LOG_FORMAT: plain
      LOG_LEVEL: DEBUG
