---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: snow-incident-ms
  namespace: xpp
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: glob:*-stg.*
spec:
  releaseName: snow-incident-ms
  forceUpgrade: true
  chart:
    repository: https://na.artifactory.swg-devops.com/artifactory/mss-helm-virtual
    name: snow-incident-ms
    version: 1.0.11-master
  values:
    service:
      targetPort: 3333
    readinessProbe:
      initialDelaySeconds: 30
    livenessProbe:
      initialDelaySeconds: 30
    image:
      repository: mss-docker.artifactory.swg-devops.com/snow-incident-ms
      tag: 1.0.11-master.0af94471
    graphite:
      enabled: true
      host: dal09-prd-statsnode-01a.sec.ibm.com
      prefix: stg.k8s.xpp
    secretName: snow-incident-ms
    ingress:
      enabled: true
      hosts:
        - host: snow-incident-ms.atl-stg.k8s.sec.ibm.com
          paths:
            - /
      tls:
        - hosts:
            - snow-incident-ms.atl-stg.k8s.sec.ibm.com
          secretName: snow-incident-ms
    config:
      server:
        port: 3333
      app:
        elasticSearch:
          baseUrl: atl-stg-eas-01a.sec.ibm.com:9200,atl-stg-eas-01b.sec.ibm.com:9200,atl-stg-eas-01c.sec.ibm.com:9200
          indexName: servicenow
          type: incident
        serviceNow:
          scheme: https
          baseUrl: secsupportstg.service-now.com
          endpoint: "/api/x_ibmip_int_inc/ws/incident"
    env:
      LOG_FORMAT: plain
      LOG_LEVEL: DEBUG