---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: vmsui-write-api
  namespace: xpp
  annotations:
    fluxcd.io/automated: "false"
    filter.fluxcd.io/chart-image: semver:1.0.2
spec:
  releaseName: vmsui-write-api
  forceUpgrade: true
  chart:
    git: git@github.ibm.com:managed-security/vmsui-write-api
    tag: 1.0.0
    path: chart
  values:
    secretName: vmsui-secrets
    secureProxy:
      repository: mss-docker.artifactory.swg-devops.com/secure_proxy_ms
      tag: 1.1.5
    image:
      repository: mss-docker.artifactory.swg-devops.com/vmsui-write-api
      tag: 1.0.2
    imagePullSecrets:
    - name: xpp-docker-registry-pull
    resources:
      limits:
        cpu: .5
      requests:
        cpu: .25
    graphite:
      enabled: true
      host: dal09-prd-statsnode-01a.sec.ibm.com
      prefix: stg.k8s.master
    ingress:
      enabled: true
      hosts:
      - host: vmsui-write-api.atl-stg.k8s.sec.ibm.com
        paths:
        - /
      tls:
      - hosts:
        - vmsui-write-api.atl-stg.k8s.sec.ibm.com

# TEMPLATE: Insert other required configuration values here
