---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: ai-alert-ip-ms
  namespace: integration
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: glob:*-integration.*
spec:
  releaseName: ai-alert-ip-ms
  forceUpgrade: false
  chart:
    repository: https://na.artifactory.swg-devops.com/artifactory/mss-helm-virtual
    name: ai-alert-ip-ms
    version: 1.0.4-integration
  values:
    service:
      targetPort: 3333
    readinessProbe:
      initialDelaySeconds: 300
    livenessProbe:
      initialDelaySeconds: 300
    image:
      repository: mss-docker.artifactory.swg-devops.com/ai-alert-ip-ms
      tag: 1.0.0-integration.f388e6a1
    graphite:
      enabled: false
      host: dal09-prd-statsnode-01a.sec.ibm.com
      prefix: dev.k8s.integration
    secretsDir: "/vault/secrets"
    serviceAccount:
      create: true
    podAnnotations:
      vault.hashicorp.com/agent-inject: 'true'
      vault.hashicorp.com/role: 'ai-alert-ip-ms'
      vault.hashicorp.com/preserve-secret-case: "true"
      vault.hashicorp.com/agent-inject-secret-app.aidb.username: "secret/modules/ai-alert-ip-ms/database"
      vault.hashicorp.com/agent-inject-template-app.aidb.username: |-
        {{- with secret "secret/modules/ai-alert-ip-ms/database" -}}{{- .Data.data.username -}}{{- end }}
      vault.hashicorp.com/agent-inject-secret-app.aidb.password: "secret/modules/ai-alert-ip-ms/database"
      vault.hashicorp.com/agent-inject-template-app.aidb.password: |-
        {{- with secret "secret/modules/ai-alert-ip-ms/database" -}}{{- .Data.data.password -}}{{- end }}
      vault.hashicorp.com/agent-inject-secret-app.aidb.jdbcurl: "secret/modules/ai-alert-ip-ms/database"
      vault.hashicorp.com/agent-inject-template-app.aidb.jdbcurl: |-
        {{- with secret "secret/modules/ai-alert-ip-ms/database" -}}{{- .Data.data.jdbcurl -}}{{- end }}
    ingress:
      enabled: true
      hosts:
      - host: ai-alert-ip-ms-integration.dal09-dev.k8s-lab.sec.ibm.com
        paths:
        - /
      tls:
      - hosts:
        - ai-alert-ip-ms-integration.dal09-dev.k8s-lab.sec.ibm.com
    config:
      server:
        port: 3333
