---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: algosec-csv-creator-ms
  namespace: integration
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: glob:*-integration.*
spec:
  releaseName: algosec-csv-creator-ms
  forceUpgrade: false
  chart:
    repository: https://na.artifactory.swg-devops.com/artifactory/mss-helm-virtual
    name: algosec-csv-creator-ms
    version: 1.0.9-integration
  values:
    service:
      targetPort: 3000
    readinessProbe:
      initialDelaySeconds: 120
    livenessProbe:
      initialDelaySeconds: 120
    image:
      repository: mss-docker.artifactory.swg-devops.com/algosec-csv-creator-ms
      tag: 1.0.13-integration.ef6e6628
    ingress:
      enabled: true
      hosts:
      - host: algosec-csv-creator-ms-integration.dal09-dev.k8s-lab.sec.ibm.com
        paths:
        - /
      tls:
      - hosts:
        - algosec-csv-creator-ms-integration.dal09-dev.k8s-lab.sec.ibm.com
    config:
      server:
        port: 3000
      env:
      LOG_FORMAT: plain
      LOG_LEVEL: DEBUG


