---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: device-enablement-aggregator
  namespace: integration
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: glob:*-integration.*
spec:
  releaseName: device-enablement-aggregator
  forceUpgrade: true
  chart:
    git: git@github.ibm.com:managed-security/device-enablement-aggregator.git
    ref: integration
    path: chart
  values:
    service:
      targetPort: 3333
    readinessProbe:
      initialDelaySeconds: 120
    livenessProbe:
      initialDelaySeconds: 120
    image:
      repository: mss-docker.artifactory.swg-devops.com/device-enablement-aggregator
      tag: 1.0.0-integration.66e6adb0
    graphite:
      enabled: false
      host: dal09-prd-statsnode-01a.sec.ibm.com
      prefix: dev.k8s.integration
    ingress:
      enabled: true
      hosts:
      - host: device-enablement-aggregator-integration.dal09-dev.k8s-lab.sec.ibm.com
        paths:
        - /
      tls:
      - hosts:
        - device-enablement-aggregator-integration.dal09-dev.k8s-lab.sec.ibm.com
    config:
      server:
        port: 3333
      app:
        credentialMS:
          scheme: https
          baseUrl: aura-credentials-ms-xpp.apps-priv.dal09-dev-ocp-01.cl.sec.ibm.com
          endpoint: /credentials/{deviceId}
        deviceEnablementMS:
          scheme: https
          baseUrl: dal09-dev-services.sec.ibm.com
          endpoint: /micro/device_enablement_values?deviceIds={deviceId}&status=Active
    env:
      LOG_FORMAT: plain
      LOG_LEVEL: DEBUG
