---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: firewall-pcr-spreadsheet-parser
  namespace: integration
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: glob:*-integration.*
spec:
  releaseName: firewall-pcr-spreadsheet-parser
  chart:
    repository: https://na.artifactory.swg-devops.com/artifactory/mss-helm-virtual
    name: firewall-pcr-spreadsheet-parser
    version: 0.0.28-integration
  values:
    service:
      targetPort: 3000
    readinessProbe:
      initialDelaySeconds: 30
    livenessProbe:
      initialDelaySeconds: 30
    image:
      repository: mss-docker.artifactory.swg-devops.com/firewall-pcr-spreadsheet-parser
      tag: 0.0.31-integration.211f96c4
    ingress:
      enabled: true
      hosts:
      - host: firewall-pcr-spreadsheet-parser-integration.dal09-dev.k8s-lab.sec.ibm.com
        paths:
        - /
      tls:
      - hosts:
        - firewall-pcr-spreadsheet-parser-integration.dal09-dev.k8s-lab.sec.ibm.com
    config:
      server:
        port: 3000
    env:
      LOG_FORMAT: plain
      LOG_LEVEL: DEBUG

