---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: machine-platform-menu-ms
  namespace: integration
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: glob:*-integration.*
spec:
  releaseName: machine-platform-menu-ms
  forceUpgrade: true
  chart:
    repository: https://na.artifactory.swg-devops.com/artifactory/mss-helm-virtual
    name: machine-platform-menu-ms
    version: 1.0.7-integration
  values:
    log:
      level: DEBUG
    service:
      targetPort: 3333
    readinessProbe:
      initialDelaySeconds: 30
    livenessProbe:
      initialDelaySeconds: 30
    image:
      repository: mss-docker.artifactory.swg-devops.com/machine-platform-menu-ms
      tag: 1.0.7-integration.3da7e577
    graphite:
      enabled: true
      host: dal09-prd-statsnode-01a.sec.ibm.com
      prefix: dev.k8s.integration
    secretsDir: "/vault/secrets"
    serviceAccount:
      create: true
    podAnnotations:
      vault.hashicorp.com/agent-inject: 'true'
      vault.hashicorp.com/role: 'machine-platform-menu-ms'
      vault.hashicorp.com/agent-inject-secret-app.elastic-search.username: "secret/modules/machine-platform-menu-ms/elastic-search"
      vault.hashicorp.com/agent-inject-template-app.elastic-search.username: |-
        {{- with secret "secret/modules/machine-platform-menu-ms/elastic-search" -}}{{- .Data.data.USERNAME -}}
        {{- end }}
      vault.hashicorp.com/agent-inject-secret-app.elastic-search.password: "secret/modules/machine-platform-menu-ms/elastic-search"
      vault.hashicorp.com/agent-inject-template-app.elastic-search.password: |-
        {{- with secret "secret/modules/machine-platform-menu-ms/elastic-search" -}}{{- .Data.data.PASSWORD -}}
        {{- end }}
    ingress:
      enabled: true
      hosts:
      - host: machine-platform-menu-ms-integration.dal09-dev.k8s-lab.sec.ibm.com
        paths:
        - /
      tls:
      - hosts:
        - machine-platform-menu-ms-integration.dal09-dev.k8s-lab.sec.ibm.com
    config:
      server:
        port: 3333
      app:
        elasticSearch:
          baseUrl: dal09-dev-solr-01a.sec.ibm.com:9200,dal09-dev-solr-01b.sec.ibm.com:9200,dal09-dev-solr-01c.sec.ibm.com:9200
          indexName: remedymenus
          type: remedymenus
    env:
      LOG_FORMAT: plain
      LOG_LEVEL: DEBUG
