---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: oi-api
  namespace: integration
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: glob:*-integration.*
spec:
  releaseName: oi-api
  chart:
    repository: https://na.artifactory.swg-devops.com/artifactory/mss-helm-virtual
    name: oi-api
    version: 0.1.8-integration
  values:
    service:
      targetPort: 8080
    readinessProbe:
      initialDelaySeconds: 30
    livenessProbe:
      initialDelaySeconds: 30
    image:
      repository: mss-docker.artifactory.swg-devops.com/oi-api
      tag: 0.2.0-integration.5eaa5d65
    ingress:
      enabled: true
      hosts:
      - host: oi-api-integration.dal09-dev.k8s-lab.sec.ibm.com
        paths:
        - /
      tls:
      - hosts:
        - oi-api-integration.dal09-dev.k8s-lab.sec.ibm.com
    config:
      server:
        port: 8080
    env:
      PORT: 8080
      LOG_FORMAT: plain
      LOG_LEVEL: DEBUG
