---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: service-roles-mapping
  namespace: integration
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: glob:*-integration.*
spec:
  releaseName: service-roles-mapping
  forceUpgrade: true
  chart:
    repository: https://na.artifactory.swg-devops.com/artifactory/mss-helm-virtual
    name: service-roles-mapping
    version: 1.0.2-integration
  values:
    service:
      targetPort: 3333
    readinessProbe:
      initialDelaySeconds: 30
    livenessProbe:
      initialDelaySeconds: 30
    image:
      repository: mss-docker.artifactory.swg-devops.com/service-roles-mapping
      tag: 1.0.2-integration.9333e3d5
    graphite:
      enabled: true
      host: dal09-prd-statsnode-01a.sec.ibm.com
      prefix: dev.k8s.integration
    secretName: service-roles-mapping
    ingress:
      enabled: true
      hosts:
      - host: service-roles-mapping-integration.dal09-dev.k8s-lab.sec.ibm.com
        paths:
        - /
      tls:
      - hosts:
        - service-roles-mapping-integration.dal09-dev.k8s-lab.sec.ibm.com
        secretName: service-roles-mapping
    config:
      server:
        port: 3333
      app:
        elasticSearch:
          baseUrl: dal09-dev-solr-01a.sec.ibm.com:9200,dal09-dev-solr-01b.sec.ibm.com:9200,dal09-dev-solr-01c.sec.ibm.com:9200
          indexName: opsservicerolesmapping
          type: servicerolesmapping
    env:
      LOG_FORMAT: plain
      LOG_LEVEL: DEBUG
