---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: slack-user-ms
  namespace: integration
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: glob:*-integration.*
spec:
  releaseName: slack-user-ms
  forceUpgrade: true
  chart:
    repository: https://na.artifactory.swg-devops.com/artifactory/mss-helm-virtual
    name: slack-user-ms
    version: 1.0.0-integration
  values:
    service:
      targetPort: 3333
    readinessProbe:
      initialDelaySeconds: 120
    livenessProbe:
      initialDelaySeconds: 120
    image:
      repository: mss-docker.artifactory.swg-devops.com/slack-user-ms
      tag: 1.0.0-integration.6a199a7d
    graphite:
      enabled: false
      host: dal09-prd-statsnode-01a.sec.ibm.com
      prefix: dev.k8s.integration
    ingress:
      enabled: true
      hosts:
      - host: slack-user-ms-integration.dal09-dev.k8s-lab.sec.ibm.com
        paths:
        - /
      tls:
      - hosts:
        - slack-user-ms-integration.dal09-dev.k8s-lab.sec.ibm.com
    config:
      server:
        port: 3333
      app:
        mssDatasource:
          jdbcUrl: jdbc:mysql://dal09-dev-mssdb-01a.sec.ibm.com:3306/slack
    secretsDir: "/vault/secrets"
    serviceAccount:
      create: true
    podAnnotations:
      vault.hashicorp.com/agent-inject: 'true'
      vault.hashicorp.com/role: 'slack-user-ms'
      vault.hashicorp.com/agent-inject-secret-app.mssDatasource.username: "secret/modules/slack-user-ms/mss-datasource"
      vault.hashicorp.com/agent-inject-template-app.mssDatasource.username: |-
        {{- with secret "secret/modules/slack-user-ms/mss-datasource" -}}{{- .Data.data.USERNAME -}}{{- end }}
      vault.hashicorp.com/agent-inject-secret-app.mssDatasource.password: "secret/modules/slack-user-ms/mss-datasource"
      vault.hashicorp.com/agent-inject-template-app.mssDatasource.password: |-
        {{- with secret "secret/modules/slack-user-ms/mss-datasource" -}}{{- .Data.data.PASSWORD -}}{{- end }}
    env:
      DOCKER_REGISTRY_PULL_SECRET_NAME: docker-registry-pull
      LOG_FORMAT: plain
      LOG_LEVEL: DEBUG
