---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: snow-problem-task-ms
  namespace: integration
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: glob:*-integration.*
spec:
  releaseName: snow-problem-task-ms
  forceUpgrade: true
  chart:
    repository: https://na.artifactory.swg-devops.com/artifactory/mss-helm-virtual
    name: snow-problem-task-ms
    version: 1.0.1-integration
  values:
    service:
      targetPort: 3333
    readinessProbe:
      initialDelaySeconds: 30
    livenessProbe:
      initialDelaySeconds: 30
    image:
      repository: mss-docker.artifactory.swg-devops.com/snow-problem-task-ms
      tag: 1.0.2-integration.d3c8b61c
    graphite:
      enabled: true
      host: dal09-prd-statsnode-01a.sec.ibm.com
      prefix: dev.k8s.integration
    secretName: snow-problem-task-ms
    ingress:
      enabled: true
      hosts:
      - host: snow-problem-task-ms-integration.dal09-dev.k8s-lab.sec.ibm.com
        paths:
        - /
      tls:
      - hosts:
        - snow-problem-task-ms-integration.dal09-dev.k8s-lab.sec.ibm.com
        secretName: snow-problem-task-ms
    config:
      server:
        port: 3333
      app:
        elasticSearch:
          baseUrl: dal09-dev-solr-01a.sec.ibm.com:9200,dal09-dev-solr-01b.sec.ibm.com:9200,dal09-dev-solr-01c.sec.ibm.com:9200
          indexName: servicenow
          type: problem_task
        serviceNow:
          scheme: https
          baseUrl: secsupportdev.service-now.com
          endpoint: "/api/x_ibmip_int_prb/ws/problem_task"
    env:
      LOG_FORMAT: plain
      LOG_LEVEL: DEBUG
