---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: snow-catalog-ms
  namespace: integration
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: glob:*-integration.*
spec:
  releaseName: snow-catalog-ms
  forceUpgrade: true
  chart:
    git: git@github.ibm.com:managed-security/snow-catalog-ms
    ref: integration
    path: chart
  values:
    service:
      targetPort: 3333
    readinessProbe:
      initialDelaySeconds: 30
    livenessProbe:
      initialDelaySeconds: 30
    image:
      repository: mss-docker.artifactory.swg-devops.com/snow-catalog-ms
      tag: 2.0.0-integration.c48df77b
    graphite:
      enabled: true
      host: dal09-prd-statsnode-01a.sec.ibm.com
      prefix: dev.k8s.integration
    secretName: snow-catalog-ms
    ingress:
      enabled: true
      hosts:
      - host: snow-catalog-ms-integration.dal09-dev.k8s-lab.sec.ibm.com
        paths:
        - /
      tls:
      - hosts:
        - snow-catalog-ms-integration.dal09-dev.k8s-lab.sec.ibm.com
        secretName: snow-catalog-ms
    config:
      server:
        port: 3333
      app:
        elasticSearch:
          baseUrl: dal09-dev-solr-01a.sec.ibm.com:9200,dal09-dev-solr-01b.sec.ibm.com:9200,dal09-dev-solr-01c.sec.ibm.com:9200
          indexName: servicenow
          type: sc_request
        serviceNow:
          scheme: https
          baseUrl: secsupportdev.service-now.com
          endpoint: "/api/x_ibmip_int_src/ws/service_request"
    env:
      LOG_FORMAT: plain
      LOG_LEVEL: DEBUG
