---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: snow-request-processor
  namespace: integration
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: glob:*-integration.*
spec:
  releaseName: snow-request-processor
  forceUpgrade: true
  chart:
    repository: https://na.artifactory.swg-devops.com/artifactory/mss-helm-virtual
    name: snow-request-processor
    version: 2.0.3-integration
  values:
    service:
      targetPort: 3333
    readinessProbe:
      initialDelaySeconds: 30
    livenessProbe:
      initialDelaySeconds: 30
    image:
      repository: mss-docker.artifactory.swg-devops.com/snow-request-processor
      tag: 2.0.3-integration.96ea8e22
    graphite:
      enabled: true
      host: dal09-prd-statsnode-01a.sec.ibm.com
      prefix: dev.k8s.integration
    secretName: snow-request-processor
    ingress:
      enabled: true
      hosts:
      - host: snow-request-processor-ms-integration.dal09-dev.k8s-lab.sec.ibm.com
        paths:
          - /
      tls:
      - hosts:
        - snow-request-processor-ms-integration.dal09-dev.k8s-lab.sec.ibm.com
        secretName: snow-request-processor
    config:
      server:
        port: 3333
      spring:
        kafka:
          bootstrap-servers: dal09-dev-kfk-01a.sec.ibm.com:9093,dal09-dev-kfk-01b.sec.ibm.com:9093,dal09-dev-kfk-01c.sec.ibm.com:9093
    env:
      LOG_FORMAT: plain
      LOG_LEVEL: DEBUG
