---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: asset-ms
  namespace: xpp
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: asset-ms
  chart:
    git: git@github.ibm.com:managed-security/asset-ms
    ref: v1.0.0
    path: chart
  values:
    log:
      level: DEBUG
    image:
      repository: mss-docker.artifactory.swg-devops.com/asset-ms
      tag: 1.0.0
    graphite:
      enabled: true
      host: atl-prd-statsnode-01a.sec.ibm.com
      prefix: prd.k8s.xpp
    secretName: asset-ms
    ingress:
      enabled: true
      hosts:
        - host: asset-ms.atl-prd.k8s.sec.ibm.com
          paths:
            - /
      tls:
        - hosts:
            - asset-ms.atl-prd.k8s.sec.ibm.com
          secretName: xdr-alert-capabilities
    config:
      asset-ms:
        mss-datasource:
          jdbc-url: jdbc:mysql://atl-prd-mssdb-01a.mss.iss.net:3306/mss
        vms-datasource:
          jdbc-url: jdbc:mysql://atl-prd-mssdb-01a.mss.iss.net:3306/vms
