---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: mdr-cbcloud-puma-drone
  namespace: xpp
  annotations:
    fluxcd.io/automated: "false"
    filter.fluxcd.io/chart-image: semver:1.1.0
spec:
  releaseName: mdr-cbcloud-puma-drone
  forceUpgrade: true
  chart:
    git: git@github.ibm.com:managed-security/mdr-cbcloud-puma-drone
    ref: master
    path: mdr-cbcloud-puma-drone
  values:
    devices:
    - PR0000000028524
    - PR0000000033465
    - PR0000000024478
    - PR0000000037089
    - PR0000000036100
    - PR0000000037622
    - PR0000000036100
    - PR0000000040380
    - PR0000000045761
    image:
      repository: mss-docker.artifactory.swg-devops.com/mdr-cbcloud-puma-drone
      tag: v1.1.0-472085dc
    secretName: "mdr-cbcloud-puma-drone"
    env:
      DOCKER_REGISTRY_PULL_SECRET_NAME: docker-registry-pull
      SERVICES_BASE_URL: services.sec.ibm.com
      SYSLOG_SERVER_IP: atl-prd-agg-01a.sec.ibm.com
      SYSLOG_SERVER_PORT: 514
