---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: response-request-listener
  namespace: xpp
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: response-request-listener
  chart:
    git: git@github.ibm.com:managed-security/response-request-listener
    ref: v1.1.4
    path: chart
  values:
    log:
      level: DEBUG
    image:
      repository: mss-docker.artifactory.swg-devops.com/response-request-listener
      tag: 1.1.4
    graphite:
      enabled: true
      host: atl-prd-statsnode-01a.sec.ibm.com
      prefix: prd.k8s.xpp
    secretName: response-request-listener
    config:
      mdr:
        services:
          baseUrl: https://services.sec.ibm.com
          timeoutSeconds: 15
        resilient:
          broker-url: ssl://atl-prd-res-36a.sec.ibm.com:65000
          org-id: 202
          queue: "actions.202.auto_response"
      spring:
        kafka:
          bootstrap-servers: atl-prd-kfk-01a.sec.ibm.com:9093, atl-prd-kfk-01b.sec.ibm.com:9093,atl-prd-kfk-01c.sec.ibm.com:9093
