---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: tdi-frontend-ui
  namespace: tdi
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: glob:*-buildbuilddevelop.*
spec:
  releaseName: tdi-frontend-ui
  forceUpgrade: true
  chart:
    repository: https://na.artifactory.swg-devops.com/artifactory/mss-helm-virtual
    name: tdi-frontend-ui
    version: 0.1.1
  values:
    image:
      repository: mss-docker.artifactory.swg-devops.com/tdi-frontend-ui
      tag: 0.1.1-buildbuilddevelop.df6a59b5
    resources:
      limits:
        cpu: 8
      requests:
        cpu: 4
    secretName: tdi-frontend-ui-secret-prd
    replicaCount: 2
    imagePullSecrets:
    - name: docker-registry-pull
    graphite:
      enabled: false
      host: atl-prd-statsnode-01a.sec.ibm.com
      prefix: stg.ocp.xpp
    # TEMPLATE: Insert other required configuration values here
