---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: active-directory-authenticator
  namespace: xpp
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: glob:*-openshift.*
spec:
  releaseName: active-directory-authenticator
  forceUpgrade: true
  chart:
    repository: https://na.artifactory.swg-devops.com/artifactory/mss-helm-virtual
    name: active-directory-authenticator
    version: 1.0.18-openshift
  values:
    image:
      repository: mss-docker.artifactory.swg-devops.com/active-directory-authenticator
      tag: 1.0.18-openshift.86e2e9f3
    imagePullSecrets:
    - name: xpp-docker-registry-pull
    env:
    - name: HOSTNAME_PREFIX
      value: active-directory-authenticator-dev-ocp
