---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: alert-data-ingestion-dome9
  namespace: xpp
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: glob:*-develop.*
spec:
  releaseName: alert-data-ingestion-dome9
  forceUpgrade: true
  chart:
    git: git@github.ibm.com:managed-security/alert-data-ingestion-dome9
    ref: develop
    path: chart
  values:
    image:
      repository: mss-docker.artifactory.swg-devops.com/alert-data-ingestion-dome9
      tag: 0.0.2-develop.f9b720d6
    imagePullSecrets:
    - name: xpp-docker-registry-pull
    resources:
      limits:
        cpu: 1
      requests:
        cpu: .5
    graphite:
      enabled: true
      host: dal09-prd-statsnode-01a.sec.ibm.com
      prefix: dev.ocp.xpp
# TEMPLATE: Insert other required configuration values here
