---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: aura-credentials-manager
  namespace: xpp
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: glob:*-dev.*
spec:
  releaseName: aura-credentials-manager
  forceUpgrade: true
  chart:
    repository: https://na.artifactory.swg-devops.com/artifactory/mss-helm-virtual
    name: aura-credentials-manager
    version: 1.0.3-dev
  values:
    image:
      repository: mss-docker.artifactory.swg-devops.com/aura-credentials-manager
      tag: 1.0.3-dev.02933321
    imagePullSecrets:
    - name: xpp-docker-registry-pull
    env:
      NODE_ENV: production
      TOKEN_INITIALS: Basic
      AUTHENTICATION_API_URL: https://services.sec.ibm.com:443/micro/authentication/login
      CREDENTIALS_API: https://aura-credentials-ms-xpp.apps-priv.dal09-dev-ocp-01.cl.sec.ibm.com
      JWT_API: https://services.sec.ibm.com:443/micro/jwt_provider
      USER_API: https://aura-user-ms-xpp.apps-priv.dal09-dev-ocp-01.cl.sec.ibm.com/users
      APP_DIRECTORY: client/build
      HTML_INDEX: index.html
    graphite:
      enabled: false
      host: dal09-prd-statsnode-01a.sec.ibm.com
      prefix: dev.ocp.xpp
