---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: authentication-ms
  namespace: xpp
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: glob:*-openshift.*
spec:
  releaseName: authentication-ms
  forceUpgrade: true
  chart:
    repository: https://na.artifactory.swg-devops.com/artifactory/mss-helm-virtual
    name: authentication-ms
    version: 1.0.23-openshift
  values:
    image:
      repository: mss-docker.artifactory.swg-devops.com/authentication-ms
      tag: 1.0.23-openshift.30ed2b81
    imagePullSecrets:
    - name: xpp-docker-registry-pull
    route:
      host: authentication-ms-xpp.apps-priv.dal09-dev-ocp-01.cl.sec.ibm.com
    env:
      env: dev
      f5Url: https://xpsws-gateway.apps-priv.dal09-dev-ocp-01.cl.sec.ibm.com
      ingressFormatString: https://%s-authenticator-integration.dal09-dev.k8s-lab.sec.ibm.com
