---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: carbonblack-sensor-ms
  namespace: xpp
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: glob:*-develop.*
spec:
  releaseName: carbonblack-sensor-ms
  forceUpgrade: true
  chart:
    git: git@github.ibm.com:managed-security/carbonblack-sensor-ms
    ref: develop
    path: chart
  values:
    image:
      repository: mss-docker.artifactory.swg-devops.com/carbonblack-sensor-ms
      tag: 0.0.1-develop.205116d8
    imagePullSecrets:
    - name: xpp-docker-registry-pull
    resources:
      limits:
        cpu: 1
      requests:
        cpu: .5
    graphite:
      enabled: true
      host: dal09-prd-statsnode-01a.sec.ibm.com
      prefix: dev.ocp.xpp
# TEMPLATE: Insert other required configuration values here
