---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: cerberus-tab-bff
  namespace: xpp
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: glob:*-master.*
spec:
  releaseName: cerberus-tab-bff
  forceUpgrade: true
  chart:
    repository: https://na.artifactory.swg-devops.com/artifactory/mss-helm-virtual
    name: cerberus-tab-bff
    version: 1.0.3-master
  values:
    image:
      repository: mss-docker.artifactory.swg-devops.com/cerberus-tab-bff
      tag: 1.0.3-master.415b6718
    imagePullSecrets:
    - name: xpp-docker-registry-pull
    graphite:
      enabled: true
      host: dal09-prd-statsnode-01a.sec.ibm.com
      prefix: dev.ocp.xpp

