apiVersion: v1
kind: Pod
metadata:
  name: cpe-password-dal09-dev-ocp-sean
  labels:
    app: cpe-password-dal09-dev-ocp-sean
  namespace: xpp
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: glob:*-ocpsean.*
spec:
  imagePullSecrets:
    - name: xpp-docker-registry-pull
  containers:
    - name: cpe-password-dal09-dev-ocp-sean
      image: mss-docker.artifactory.swg-devops.com/cpe_passwords:0.0.4-ocpsean.c5a6ccc0
      command: [ "/bin/bash", "-c", "--" ]
      args: [ "while true; do sleep 30; done;" ]
