apiVersion: v1
kind: Pod
metadata:
  name: cpe-password-dal09-dev-ocp
  labels:
    app: cpe-password-dal09-dev-ocp
  namespace: xpp
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: glob:*-container.*
spec:
  imagePullSecrets:
    - name: xpp-docker-registry-pull
  containers:
    - name: cpe-password-dal09-dev-ocp
      image: mss-docker.artifactory.swg-devops.com/cpe_passwords:0.0.1-container.bcf4d6be
      command: [ "/bin/bash", "-c", "--" ]
      args: [ "while true; do sleep 30; done;" ]
