---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: customer-role-permissions-ms
  namespace: xpp
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: glob:*-openshift.*
spec:
  releaseName: customer-role-permissions-ms
  forceUpgrade: true
  chart:
    repository: https://na.artifactory.swg-devops.com/artifactory/mss-helm-virtual
    name: customer-role-permissions-ms
    version: 1.1.28-openshift
  values:
    image:
      repository: mss-docker.artifactory.swg-devops.com/customer-role-permissions-ms
      tag: 1.1.28-openshift.b434d538
    imagePullSecrets:
    - name: xpp-docker-registry-pull
    route:
      enabled: true
      host: customer-role-permissions-ms-xpp.apps-priv.dal09-dev-ocp-01.cl.sec.ibm.com
    env:
      ENV: dev
      vault_url: https://dev-vault.sec.ibm.com:8200
      vault_role_id: 29b643f0-c262-cb2a-f878-c060efe0cbee
      vault_secret_id: a5fc1e5c-7d0f-5176-b7ef-2eb1ce6256a8
      vault_path: secret/modules/customer_role_permissions_ms/
      customer_contact_ms: https://customer-contact-ms-xpp.apps-priv.dal09-dev-ocp-01.cl.sec.ibm.com/customer_contact
      elastic_search_client_transport_hosts: dal09-dev-solr-01a.sec.ibm.com,dal09-dev-solr-01b.sec.ibm.com,dal09-dev-solr-01c.sec.ibm.com
      elastic_search_cluster_name: elastic_dal09dev
      elastic_search_mss_ssl_server_keyStore: /opt/mssdev/customer_role_permissions_ms/conf/esclientkeystore
      elastic_search_mss_ssl_server_trustStore: /opt/mssdev/customer_role_permissions_ms/conf/esclienttruststore
      elastic_search_client_type: transport
      elastic_search_port: 9300
      elastic_search_client_ping_timeout_seconds: 60
      elastic_search_client_ssl_protocol_version: TLSv1.2
      elastic_search_ssl_enabled: true
      elastic_search_rest_enabled: false
      elastic_search_forceNativeClientAuth: true
      elastic_search_forceRestClientAuth: false
