---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: customer-enablement-values-ms
  namespace: xpp
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: glob:*-openshift.*
spec:
  releaseName: customer-enablement-values-ms
  forceUpgrade: true
  chart:
    repository: https://na.artifactory.swg-devops.com/artifactory/mss-helm-virtual
    name: customer-enablement-values-ms
    version: 1.1.44-openshift
  values:
    image:
      repository: mss-docker.artifactory.swg-devops.com/customer-enablement-values-ms
      tag: 1.1.45-openshift.55da1b81
    imagePullSecrets:
    - name: xpp-docker-registry-pull
    env:
      elastic_search_ms: https://es-search-ms-integration.dal09-dev.k8s-lab.sec.ibm.com/es_search

