---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: dams-backups-ms
  namespace: xpp
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: glob:*-master.*
spec:
  releaseName: dams-backups-ms
  forceUpgrade: true
  chart:
    repository: https://na.artifactory.swg-devops.com/artifactory/mss-helm-virtual
    name: dams-backups-ms
    version: 1.0.1-master
  values:
    image:
      repository: mss-docker.artifactory.swg-devops.com/dams-backups-ms
      tag: 1.0.1-master.1dece76a
    imagePullSecrets:
    - name: example-docker-registry-pull
    graphite:
      enabled: true
      host: dal09-prd-statsnode-01a.sec.ibm.com
      prefix: dev.ocp.example
    # TEMPLATE: Insert other required configuration values here
