apiVersion: v1
kind: Pod
metadata:
  name: dbrep-manual-pod-for-testing
  labels:
    app: dbrep-manual-pod-for-testing
  namespace: xpp
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: glob:*-container.*
spec:
  imagePullSecrets:
    - name: xpp-docker-registry-pull
  containers:
    - name: dbrep-manual-pod-for-testing
      image: mss-docker.artifactory.swg-devops.com/databasereplication:1.2.8-container.e6e92b8a
      command: [ "/bin/bash", "-c", "--" ]
      args: [ "while true; do sleep 30; done;" ]
      env:
        - name: STACK
          value: dev
      resources:
        limits:
          cpu: 3
          memory: 5120Mi
        requests:
          cpu: 1
          memory: 128Mi
      #propertiesViaConfigMap:
      #  enabled: true
      #  volumeMounts:
      #    - name: xforce-config
      #      mountPath: /opt/mssdev/properties
      #  volumes:
      #    - name: xforce-config
      #      configMap:
      #        name: dbrep-xforce-config
