---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: demo
  namespace: xpp
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: glob:*-master.*
spec:
  releaseName: demo
  forceUpgrade: true
  chart:
    repository: https://na.artifactory.swg-devops.com/artifactory/mss-helm-virtual
    name: demo
    version: 0.0.1-master
  values:
    image:
      repository: mss-docker.artifactory.swg-devops.com/demo
      tag: 0.0.1-master.b3583e05
