---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: device-enablement-values-ms
  namespace: xpp
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: glob:*-openshift.*
spec:
  releaseName: device-enablement-values-ms
  forceUpgrade: false
  chart:
    repository: https://na.artifactory.swg-devops.com/artifactory/mss-helm-virtual
    name: device-enablement-values-ms
    version: 1.0.6-openshift
  values:
    image:
      repository: mss-docker.artifactory.swg-devops.com/device-enablement-values-ms
      tag: 1.0.6-openshift.95700444
    imagePullSecrets:
    - name: xpp-docker-registry-pull
    route:
      host: device-enablement-values-ms-xpp.apps-priv.dal09-dev-ocp-01.cl.sec.ibm.com
    env:
      environment: dev
      elasticSearchService: https://es-search-ms-xpp.apps-priv.dal09-dev-ocp-01.cl.sec.ibm.com/es_search
      dataPermissionsService: https://customer-data-permissions-ms-xpp.apps-priv.dal09-dev-ocp-01.cl.sec.ibm.com/customer_data_permissions


