---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: endpoint-security-frontend
  namespace: xpp
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: glob:*-review.*
spec:
  releaseName: endpoint-security-frontend
  forceUpgrade: true
  chart:
    repository: https://na.artifactory.swg-devops.com/artifactory/mss-helm-virtual
    name: endpoint-security-frontend
    version: 0.0.2-policyreview
  values:
    image:
      repository: mss-docker.artifactory.swg-devops.com/endpoint-security-frontend
      tag: 0.0.2-policyreview.4df239cf
    resources:
      requests:
        cpu: 0.5
        memory: 1Gi
      limits:
        cpu: 2
        memory: 3Gi
    imagePullSecrets:
    - name: xpp-docker-registry-pull
    graphite:
      enabled: false
      host: dal09-prd-statsnode-01a.sec.ibm.com
      prefix: dev.ocp.xpp
    # TEMPLATE: Insert other required configuration values here.
