---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: es-json-ms
  namespace: xpp
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: glob:*-openshift.*
spec:
  releaseName: es-json-ms
  forceUpgrade: true
  chart:
    repository: https://na.artifactory.swg-devops.com/artifactory/mss-helm-virtual
    name: es-json-ms
    version: 1.0.13-openshift
  values:
    image:
      repository: mss-docker.artifactory.swg-devops.com/es-json-ms
      tag: 1.0.13-openshift.bdb4dea4
    imagePullSecrets:
    - name: xpp-docker-registry-pull
    env:
      environment: dev
      elastic_search_hosts: https://dal09-dev-esmasdata-02a.sec.ibm.com:9200,https://dal09-dev-esmasdata-02b.sec.ibm.com:9200,https://dal09-dev-esmasdata-02c.sec.ibm.com:9200
      vault_url: https://dev-vault.sec.ibm.com:8200
      vault_role_id: 62994a24-991b-8e36-4bda-8d2bf4d05bb1
      vault_secret_id: eeccb018-77d2-6550-217b-a51a2c3cfbfe
      vault_path: secret/modules/es_json_ms/
