---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: iss-eng-bot
  namespace: xpp
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: glob:*-container.*
spec:
  releaseName: iss-eng-bot-dal09-dev-ocp
  forceUpgrade: true
  chart:
    repository: https://na.artifactory.swg-devops.com/artifactory/mss-helm-virtual
    name: iss-eng-bot
    version: 1.1.37-container
  values:
    image:
      repository: mss-docker.artifactory.swg-devops.com/iss-eng-bot
      tag: 1.2.3-container.f78b62df
    imagePullSecrets:
    - name: xpp-docker-registry-pull
    env:
    - name: STACK
      value: dev
    # TEMPLATE: Insert other required configuration values here
