---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: jira-automation
  namespace: xpp
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: glob:*master*
spec:
  releaseName: jira-automation
  forceUpgrade: true
  chart:
    git: git@github.ibm.com:mss-qa/jira-automation
    ref: master
    path: chart
  values:
    image:
      repository: mss-docker.artifactory.swg-devops.com/jira-automation
      tag: 1.0.0-master.e02fa7ac
    imagePullSecrets:
    - name: xpp-docker-registry-pull
    resources:
      limits:
        cpu: .5
      requests:
        cpu: .25
    graphite:
      enabled: true
      host: dal09-prd-statsnode-01a.sec.ibm.com
      prefix: dev.ocp.xpp
# TEMPLATE: Insert other required configuration values here
