---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: lms-log-source-ms
  namespace: xpp
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: glob:*-integration.*
spec:
  releaseName: lms-log-source-ms
  forceUpgrade: true
  chart:
    git: git@github.ibm.com:managed-security/lms-log-source-ms
    ref: integration
    path: chart
  values:
    image:
      repository: mss-docker.artifactory.swg-devops.com/lms-log-source-ms
      tag: 1.0.0-integration.246de6ec
    imagePullSecrets:
    - name: xpp-docker-registry-pull
    resources:
      limits:
        cpu: 1
      requests:
        cpu: .5
    graphite:
      enabled: true
      host: dal09-prd-statsnode-01a.sec.ibm.com
      prefix: dev.ocp.xpp
    log:
      level: TRACE
      format: plain
    config:
      app:
        redis-host: "lmscache.redis.svc.cluster.local"
        redis-port: 11366
