---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: lms-tcp-cleartext-endpoint
  namespace: xpp
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: glob:*-integration.*
spec:
  releaseName: lms-tcp-cleartext-endpoint
  forceUpgrade: true
  chart:
    git: git@github.ibm.com:managed-security/lms-tcp-cleartext-endpoint
    ref: integration
    path: chart
  values:
    image:
      repository: mss-docker.artifactory.swg-devops.com/lms-tcp-cleartext-endpoint
      tag: 1.0.0-integration.83e56902
    imagePullSecrets:
    - name: xpp-docker-registry-pull
    resources:
      limits:
        cpu: 2.5
      requests:
        cpu: 1
    graphite:
      enabled: true
      host: dal09-prd-statsnode-01a.sec.ibm.com
      prefix: dev.ocp.xpp
    log:
      level: INFO
      format: plain
    config:
      listener:
        port: 8990
        connection-backlog: 50
        buffer-size: 32768
        message-url: "pulsar://pulsar-proxy.pulsar.svc.cluster.local:6650/"
        topic-name: "qradar-raw-traffic"
        unknown-topic-name: "unknown-tcp-traffic"
        unknown-directory: "/unknown"
        compression-type: lz4
