---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: log-storage-ms
  namespace: xpp
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: glob:*-integration.*
spec:
  releaseName: log-storage-ms
  forceUpgrade: true
  chart:
    git: git@github.ibm.com:managed-security/log-storage-ms
    ref: integration
    path: chart
  values:
    image:
      repository: mss-docker.artifactory.swg-devops.com/log-storage-ms
      tag: 1.0.0-integration.474b2a48
    imagePullSecrets:
    - name: xpp-docker-registry-pull
    resources:
      limits:
        cpu: 3
      requests:
        cpu: 2
    graphite:
      enabled: true
      host: dal09-prd-statsnode-01a.sec.ibm.com
      prefix: dev.ocp.xpp
    log:
      level: INFO
      format: plain
    config:
      app:
        messaging-url: 'pulsar://pulsar-proxy.pulsar.svc.cluster.local:6650'
        topic-name: 'qradar-raw-device-traffic'
        unknown-topic-name: 'unknown-traffic'
        unknown-directory: '/opt/app-root/unknown'
        log-directory: '/opt/app-root/logs'
        pulsar-subscription-name: 'log-storage'
        max-num-messages: 1000
        max-batch-time-in-seconds: 1
