---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: mars-collection-request-ms
  namespace: xpp
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: glob:*-OpenShift.*
spec:
  releaseName: mars-collection-request-ms
  forceUpgrade: true
  chart:
    git: git@github.ibm.com:managed-security/mars_collection_request_ms
    ref: 1.0.0
    path: chart
  values:
    image:
      repository: mss-docker.artifactory.swg-devops.com/mars_collection_request_ms
      tag: 1.0.0-OpenShift-snapshot
    imagePullSecrets:
    - name: xpp-docker-registry-pull
    resources:
      limits:
        cpu: .5
      requests:
        cpu: .25
    graphite:
      enabled: true
      host: dal09-prd-statsnode-01a.sec.ibm.com
      prefix: dev.ocp.xpp
    # TEMPLATE: Insert other required configuration values here