---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: maslak-nodejs
  namespace: xpp
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: glob:*-master.*
spec:
  releaseName: maslak-nodejs
  forceUpgrade: true
  chart:
    repository: https://na.artifactory.swg-devops.com/artifactory/mss-helm-virtual
    name: maslak-nodejs
    version: 1.0.0-master
  values:
    image:
      repository: mss-docker.artifactory.swg-devops.com/maslak-nodejs
      tag: 1.0.0-master.41e4c7a8
    imagePullSecrets:
    - name: example-docker-registry-pull
    graphite:
      enabled: true
      host: dal09-prd-statsnode-01a.sec.ibm.com
      prefix: dev.ocp.xpp
    # TEMPLATE: Insert other required configuration values here
