---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: microservice-automated-test
  namespace: xpp
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: glob:*-master.*
spec:
  releaseName: microservice-automated-test
  forceUpgrade: true
  test:
    enable: true
  chart:
    repository: https://na.artifactory.swg-devops.com/artifactory/mss-helm-virtual
    name: microservice-automated-test
    version: 1.0.12-master
  values:
    image:
      repository: mss-docker.artifactory.swg-devops.com/microservice-automated-test
      tag: 1.0.12-master.a5ea3b2c
    imagePullSecrets:
    - name: xpp-docker-registry-pull
    resources:
      limits:
        cpu: .5
      requests:
        cpu: .25
    env:
      name: ENV
      value: KSA
    graphite:
      enabled: true
      host: dal09-prd-statsnode-01a.sec.ibm.com
      prefix: dev.ocp.xpp
    # TEMPLATE: Insert other required configuration values here
