---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: mss-token-authenticator
  namespace: xpp
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: glob:*-openshift.*
spec:
  releaseName: mss-token-authenticator
  forceUpgrade: true
  chart:
    repository: https://na.artifactory.swg-devops.com/artifactory/mss-helm-virtual
    name: mss-token-authenticator
    version: 1.0.22-openshift
  values:
    image:
      repository: mss-docker.artifactory.swg-devops.com/mss-token-authenticator
      tag: 1.0.22-openshift.6ea222b1
    imagePullSecrets:
    - name: xpp-docker-registry-pull
    env:
      env: dev
      environment: dev
      es_hosts: dal09-dev-solr-01a.sec.ibm.com,dal09-dev-solr-01b.sec.ibm.com,dal09-dev-solr-01c.sec.ibm.com
      es_port: 9200
      es_user: mssesadm
      vault_role_id: 72f9018f-db1b-71ac-3d9c-2ce8af7eb85b
      vault_secret_id: ab01226d-3be7-f878-1ed0-5957adbc710d
      vault_path: secret/modules/mss_token_authenticator/
      vault_url: https://dev-vault.sec.ibm.com:8200
