---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: nodejs-cerberus
  namespace: xpp
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: glob:*-master.*
spec:
  releaseName: nodejs-cerberus
  forceUpgrade: true
  chart:
    repository: https://na.artifactory.swg-devops.com/artifactory/mss-helm-virtual
    name: nodejs-cerberus
    version: 1.0.0-master
  values:
    image:
      repository: mss-docker.artifactory.swg-devops.com/nodejs-cerberus
      tag: 1.0.1-master.763b70f6
    imagePullSecrets:
    - name: xpp-docker-registry-pull
    graphite:
      enabled: true
      host: dal09-prd-statsnode-01a.sec.ibm.com
      prefix: dev.ocp.xpp
    readinessProbe:
      initialDelaySeconds: 300
      periodSeconds: 20
    livenessProbe:
      initialDelaySeconds: 300
      periodSeconds: 20
