---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: oi-api
  namespace: xpp
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: glob:*-integration.*
spec:
  releaseName: oi-api
  chart:
    repository: https://na.artifactory.swg-devops.com/artifactory/mss-helm-virtual
    name: oi-api
    version: 0.1.2-integration
  values:
    image:
      repository: mss-docker.artifactory.swg-devops.com/oi-api
      tag: 0.2.0-integration.5eaa5d65
    service:
      targetPort: 8080
    readinessProbe:
      initialDelaySeconds: 30
    livenessProbe:
      initialDelaySeconds: 30
    serviceAccount:
      create: true
    route:
      enabled: true
      host: oi-api.apps-priv.dal09-dev-ocp-01.cl.sec.ibm.com
    config:
      server:
        port: 8080
    env:
      LOG_FORMAT: plain
      LOG_LEVEL: DEBUG
