---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: palo-alto-ms
  namespace: xpp
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: glob:*-develop.*
spec:
  releaseName: palo-alto-ms
  forceUpgrade: true
  chart:
    git: git@github.ibm.com:managed-security/palo-alto-ms
    ref: develop
    path: chart
  values:
    image:
      repository: mss-docker.artifactory.swg-devops.com/palo-alto-ms
      tag: 0.0.1-develop.1b4e3563
    imagePullSecrets:
    - name: xpp-docker-registry-pull
    resources:
      limits:
        cpu: .5
      requests:
        cpu: .25
    graphite:
      enabled: true
      host: dal09-prd-statsnode-01a.sec.ibm.com
      prefix: dev.ocp.xpp
    # TEMPLATE: Insert other required configuration values here
