---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: pass-hashing-ms
  namespace: xpp
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: glob:*-openshift.*
spec:
  releaseName: pass-hashing-ms
  forceUpgrade: true
  chart:
    repository: https://na.artifactory.swg-devops.com/artifactory/mss-helm-virtual
    name: pass-hashing-ms
    version: 1.1.3-openshift
  values:
    image:
      repository: mss-docker.artifactory.swg-devops.com/pass-hashing-ms
      tag: 1.1.3-openshift.936e657e
    imagePullSecrets:
    - name: xpp-docker-registry-pull
    env:
      vault_url: https://dev-vault.sec.ibm.com:8200
      vault_role_id: 1abc9fae-78df-5c30-dc92-08a883b05081
      vault_secret_id: ec18cf97-4937-2f78-6c5b-2cf619ee8915
      vault_path: secret/modules/pass-hashing-ms/
      mysql_db: mss
      mysql_port: 3306
      mysql_host: dal09-dev-mssdb-01a.sec.ibm.com
      mysql_maxPoolSize: 10
