---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: plat-628-java
  namespace: xpp
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: glob:*-master.*
spec:
  releaseName: plat-628-java
  forceUpgrade: true
  chart:
    repository: https://na.artifactory.swg-devops.com/artifactory/mss-helm-virtual
    name: plat-628-java
    version: 0.0.1-master
  values:
    image:
      repository: mss-docker.artifactory.swg-devops.com/plat-628-java
      tag: 0.0.1-master.5763ce9a
    imagePullSecrets:
    - name: example-docker-registry-pull
    graphite:
      enabled: true
      host: dal09-prd-statsnode-01a.sec.ibm.com
      prefix: dev.ocp.example
    # TEMPLATE: Insert other required configuration values here
