---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: plat-628-njs
  namespace: xpp
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: glob:*-master.*
spec:
  releaseName: plat-628-njs
  forceUpgrade: true
  chart:
    repository: https://na.artifactory.swg-devops.com/artifactory/mss-helm-virtual
    name: plat-628-njs
    version: 1.0.0-master
  values:
    image:
      repository: mss-docker.artifactory.swg-devops.com/plat-628-njs
      tag: 1.0.0-master.ccbd5c82
    imagePullSecrets:
    - name: example-docker-registry-pull
    graphite:
      enabled: true
      host: dal09-prd-statsnode-01a.sec.ibm.com
      prefix: dev.ocp.example
