apiVersion: v1
kind: Pod
metadata:
  name: signaturecategorizationtool-job-dal09-dev-ocp-01
  labels:
    app: signaturecategorizationtool-job-dal09-dev-ocp-01
  namespace: xpp
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: glob:*-container.*
  
spec:
  imagePullSecrets:
    - name: xpp-docker-registry-pull
  containers:
    - name: signaturecategorizationtool-job-dal09-dev-ocp-01
      image: mss-docker.artifactory.swg-devops.com/signaturecategorizationtool:1.3.1-container.fe06380e
      command: [ "/bin/bash", "-c", "--" ]
      args: [ "while true; do sleep 30; done;" ]
      volumeMounts: 
        - mountPath: /opt/mssdev/SignatureCategorizationTool/bin/data/
          name: sigcategtool-pvc
  imagePullSecrets: 
    - name: xpp-docker-registry-pull
  volumes: 
    - name: sigcategtool-pvc
      persistentVolumeClaim: 
        claimName: signaturecategorizationtool-fs     
