---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: signaturecategtool-buildindex-dal09-dev-ocp-01
  namespace: xpp
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: glob:*-container.*
spec:
  releaseName: signaturecategtool-buildindex-dal09-dev-ocp-01
  forceUpgrade: true
  chart:
    repository: https://na.artifactory.swg-devops.com/artifactory/mss-helm-virtual
    name: signaturecategorizationtool
    version: 1.3.1-container
  values:
    image:
      repository: mss-docker.artifactory.swg-devops.com/signaturecategorizationtool
      tag: 1.3.1-container.7b753038
    imagePullSecrets:
    - name: xpp-docker-registry-pull
    schedule: "0 19 * * 5"
    args:
    - /opt/mssdev/SignatureCategorizationTool/bin/SignatureCategorizationTool.sh
    - buildindex
    - input=service
    - categoryFilter=only_non_empty
    - descriptionFilter=only_non_empty
    graphite:
      enabled: true
      host: dal09-prd-statsnode-01a.sec.ibm.com
      prefix: dev.ocp.xpp
