---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: tdi-backend-scheduler
  namespace: xpp
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: glob:*-master.*
spec:
  releaseName: tdi-backend-scheduler
  forceUpgrade: true
  chart:
    repository: https://na.artifactory.swg-devops.com/artifactory/mss-helm-virtual
    name: tdi-backend-scheduler
    version: 0.1.3
  values:
    image:
      repository: mss-docker.artifactory.swg-devops.com/tdi-backend-scheduler
      tag: 0.1.3-master.0ecc829b
    imagePullSecrets:
    - name: xpp-docker-registry-pull
    # TEMPLATE: Insert other required configuration values here
