---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: tdi-backend-db
  namespace: xpp
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: glob:*-ctgit0001.*
spec:
  releaseName: tdi-backend-db
  forceUpgrade: true
  chart:
    repository: https://na.artifactory.swg-devops.com/artifactory/mss-helm-virtual
    name: tdi-backend-db
    version: 0.1.0
  values:
    image:
      repository: mss-docker.artifactory.swg-devops.com/tdi-backend-db
      tag: 0.1.2-ctgit0001.fa4743b3
    config:
      MYSQL_POOL_SIZE: 5
      MAX_WORKERS: 6
      GRACEFUL_TIMEOUT: 120
      TIMEOUT: 1200
      KEEP_ALIVE: 15
      THREADS: 2
    resources:
      limits:
        cpu: 4
      requests:
        cpu: 2
    imagePullSecrets:
    - name: xpp-docker-registry-pull
    graphite:
      enabled: false
      host: dal09-prd-statsnode-01a.sec.ibm.com
      :WQprefix: dev.ocp.xpp
    # TEMPLATE: Insert other required configuration values here
