---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: vmsui2
  namespace: xpp
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: glob:*-devtest2.*
spec:
  releaseName: vmsui2
  forceUpgrade: true
  chart:
    git: git@github.ibm.com:managed-security/vmsui
    ref: dev-test2
    path: chart
  values:
    config:
      API_URL: http://vmsui-api2:8080
    image:
      repository: mss-docker.artifactory.swg-devops.com/vmsui
      tag: 2020.12.10-devtest2.67a1cfdf
    imagePullSecrets:
    - name: xpp-docker-registry-pull
    resources:
      limits:
        cpu: .5
      requests:
        cpu: .25
    graphite:
      enabled: true
      host: dal09-prd-statsnode-01a.sec.ibm.com
      prefix: dev.ocp.xpp
      port: 2003

# TEMPLATE: Insert other required configuration values here
