---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: xfesstools07
  namespace: xpp
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: glob:*-master.*
spec:
  releaseName: xfesstools07
  forceUpgrade: true
  chart:
    repository: https://na.artifactory.swg-devops.com/artifactory/mss-helm-virtual
    name: xfesstools07
    version: 0.0.0-master
  values:
    image:
      repository: mss-docker.artifactory.swg-devops.com/xfesstools07
      tag: 0.0.0-master.8cf7b4d0
    imagePullSecrets:
    - name: xpp-docker-registry-pull
    resources:
      limits:
        cpu: .5
      requests:
        cpu: .25
    graphite:
      enabled: true
      host: dal09-prd-statsnode-01a.sec.ibm.com
      prefix: dev.ocp.xpp
    # TEMPLATE: Insert other required configuration values here
