---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: horizon-reports
  namespace: xpp
  annotations:
    fluxcd.io/automated: "false"
spec:
  targetNamespace: horizon
  releaseName: horizon-reports
  chart:
    git: git@github.ibm.com:managed-security/horizon-reports
    ref: v1.0.1
    path: chart
  values:
    service:
      port: 3000
    image:
      repository: mss-docker.artifactory.swg-devops.com/horizon-reports
      tag: 1.0.1
    log:
      level: "debug"
    config:
      PORT: 3000
      SERVICES_URL: "https://services.sec.ibm.com"
    serviceAccount:
      create: true
    secretsDir: "/vault/secrets"
    podAnnotations:
      vault.hashicorp.com/agent-inject: "true"
      vault.hashicorp.com/preserve-secret-case: "true"
      vault.hashicorp.com/role: "horizon-reports"
      vault.hashicorp.com/agent-inject-secret-INTRA_ACCESS_KEY: "secret/data/modules/horizon-reports/auth"
      vault.hashicorp.com/agent-inject-template-INTRA_ACCESS_KEY: |-
        {{- with secret "secret/data/modules/horizon-reports/auth" -}}{{- .Data.data.INTRA_ACCESS_KEY -}}{{- end }}
      vault.hashicorp.com/agent-inject-secret-MSS_TOKEN: "secret/data/modules/horizon-reports/client/services/auth"
      vault.hashicorp.com/agent-inject-template-MSS_TOKEN: |-
        {{- with secret "secret/data/modules/horizon-reports/client/services/auth" -}}{{- .Data.data.TOKEN -}}{{- end }}
