---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: xforcetomss-atl-prd-job
  namespace: xpp
  annotations:
    fluxcd.io/automated: "false"
    filter.fluxcd.io/chart-image: glob:*-master.*
spec:
  releaseName: xforcetomss-atl-prd-job
  forceUpgrade: true
  chart:
    repository: https://na.artifactory.swg-devops.com/artifactory/mss-helm-virtual
    name: databasereplication
    version: 1.3.1-master
  values:
    image:
      repository: mss-docker.artifactory.swg-devops.com/databasereplication
      tag: 1.3.1-master.f06c5b04
    imagePullSecrets:
    - name: docker-registry-pull
    schedule: "46 6 * * *"
    args:
      path: /opt/mssdev/DatabaseReplication/bin/XforceToMssReplication-parallel.sh
      cmd: run
    env:
      name: STACK
      value: prd
    env-extras:
      - name: JOB_INDEX
        value: 1-6
    propertiesViaConfigMap:
      enabled: true
      volumeMounts:
      - name: app-data
        mountPath: /opt/mssdev/properties
      volumes:
      - name: app-data
        configMap:
          name: dbrep-xforce-config