---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: mss-spring-eureka-server
  namespace: xpp
  annotations:
    fluxcd.io/automated: "false"
    filter.fluxcd.io/chart-image: glob:*-master.*
spec:
  releaseName: mss-spring-eureka-server
  forceUpgrade: true
  chart:
    repository: https://na.artifactory.swg-devops.com/artifactory/mss-helm-virtual
    name: mss-spring-eureka-server
    version: 0.2.0-master
  values:
    image:
      repository: mss-docker.artifactory.swg-devops.com/mss-spring-eureka-server
      tag: 0.2.0-master.faa164c3
    imagePullSecrets:
    - name: docker-registry-pull
    graphite:
      enabled: false
      host: atl-prd-statsnode-01a.sec.ibm.com
      prefix: prd.ocp.xpp
    # TEMPLATE: Insert other required configuration values here
