---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: entity-to-permissible-ms
  namespace: xpp
  annotations:
    fluxcd.io/automated: "false"
    filter.fluxcd.io/chart-image: glob:*-master.*
spec:
  releaseName: entity-to-permissible-ms
  forceUpgrade: true
  chart:
    repository: https://na.artifactory.swg-devops.com/artifactory/mss-helm-virtual
    name: entity-to-permissible-ms
    version: 1.0.7-master
  values:
    service:
      targetPort: 3333
    readinessProbe:
      initialDelaySeconds: 30
    livenessProbe:
      initialDelaySeconds: 30
    image:
      repository: mss-docker.artifactory.swg-devops.com/entity-to-permissible-ms
      tag: 1.0.7-master.75cb743a
    graphite:
      enabled: true
      host: atl-prd-statsnode-01a.sec.ibm.com
      prefix: prd.k8s.xpp
    secretsDir: "/vault/secrets"
    serviceAccount:
      create: true
    podAnnotations:
      vault.hashicorp.com/agent-inject: 'true'
      vault.hashicorp.com/role: 'entity-to-permissible-ms'
      vault.hashicorp.com/agent-inject-secret-app.elastic-search.username: "secret/modules/entity-to-permissible-ms/elastic-search"
      vault.hashicorp.com/agent-inject-template-app.elastic-search.username: |-
        {{- with secret "secret/modules/entity-to-permissible-ms/elastic-search" -}}{{- .Data.data.USERNAME -}}
        {{- end }}
      vault.hashicorp.com/agent-inject-secret-app.elastic-search.password: "secret/modules/entity-to-permissible-ms/elastic-search"
      vault.hashicorp.com/agent-inject-template-app.elastic-search.password: |-
        {{- with secret "secret/modules/entity-to-permissible-ms/elastic-search" -}}{{- .Data.data.PASSWORD -}}
        {{- end }}
    ingress:
      enabled: true
      hosts:
        - host: entity-to-permissible-ms.atl-prd.k8s.sec.ibm.com
          paths:
            - /
      tls:
        - hosts:
            - entity-to-permissible-ms.atl-prd.k8s.sec.ibm.com
    config:
      server:
        port: 3333
      app:
        elasticSearch:
          baseUrl: atl-prd-eas-01a.sec.ibm.com:9200,atl-prd-eas-01b.sec.ibm.com:9200,atl-prd-eas-01c.sec.ibm.com:9200
          indexName: opsportalpermission
          type: portalpermission
    env:
      LOG_FORMAT: plain
      LOG_LEVEL: DEBUG
