---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: slack-user-ms
  namespace: xpp
  annotations:
    fluxcd.io/automated: "false"
    filter.fluxcd.io/chart-image: glob:*-master.*
spec:
  releaseName: slack-user-ms
  forceUpgrade: true
  chart:
    repository: https://na.artifactory.swg-devops.com/artifactory/mss-helm-virtual
    name: slack-user-ms
    version: 1.0.0-master
  values:
    service:
      targetPort: 3333
    readinessProbe:
      initialDelaySeconds: 30
    livenessProbe:
      initialDelaySeconds: 30
    image:
      repository: mss-docker.artifactory.swg-devops.com/slack-user-ms
      tag: 1.0.0-master.0a978edc
    graphite:
      enabled: true
      host: atl-prd-statsnode-01a.sec.ibm.com
      prefix: prd.k8s.xpp
    ingress:
      enabled: true
      hosts:
      - host: slack-user-ms.atl-prd.k8s.sec.ibm.com
        paths:
        - /
      tls:
      - hosts:
        - slack-user-ms.atl-prd.k8s.sec.ibm.com
    secretsDir: "/vault/secrets"
    serviceAccount:
      create: true
    podAnnotations:
      vault.hashicorp.com/agent-inject: 'true'
      vault.hashicorp.com/role: 'slack-user-ms'
      vault.hashicorp.com/agent-inject-secret-app.mssDatasource.username: "secret/modules/slack-user-ms/mss-datasource"
      vault.hashicorp.com/agent-inject-template-app.mssDatasource.username: |-
        {{- with secret "secret/modules/slack-user-ms/mss-datasource" -}}{{- .Data.data.USERNAME -}}{{- end }}
      vault.hashicorp.com/agent-inject-secret-app.mssDatasource.password: "secret/modules/slack-user-ms/mss-datasource"
      vault.hashicorp.com/agent-inject-template-app.mssDatasource.password: |-
        {{- with secret "secret/modules/slack-user-ms/mss-datasource" -}}{{- .Data.data.PASSWORD -}}{{- end }}
    config:
      server:
        port: 3333
      app:
        mssDatasource:
          jdbcUrl: jdbc:mysql://atl-prd-mssdb-01a.mss.iss.net:3306/slack
    env:
      DOCKER_REGISTRY_PULL_SECRET_NAME: docker-registry-pull
      LOG_FORMAT: plain
      LOG_LEVEL: DEBUG
