---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: snow-problem-ms
  namespace: xpp
  annotations:
    fluxcd.io/automated: "false"
    filter.fluxcd.io/chart-image: glob:*-master.*
spec:
  releaseName: snow-problem-ms
  forceUpgrade: true
  chart:
    repository: https://na.artifactory.swg-devops.com/artifactory/mss-helm-virtual
    name: snow-problem-ms
    version: 2.0.9-master
  values:
    service:
      targetPort: 3333
    readinessProbe:
      initialDelaySeconds: 30
    livenessProbe:
      initialDelaySeconds: 30
    image:
      repository: mss-docker.artifactory.swg-devops.com/snow-problem-ms
      tag: 2.0.9-master.817b925a
    graphite:
      enabled: true
      host: atl-prd-statsnode-01a.sec.ibm.com
      prefix: prd.k8s.xpp
    secretName: snow-problem-ms
    ingress:
      enabled: true
      hosts:
        - host: snow-problem-ms.atl-prd.k8s.sec.ibm.com
          paths:
            - /
      tls:
        - hosts:
            - snow-problem-ms.atl-prd.k8s.sec.ibm.com
          secretName: snow-problem-ms
    config:
      server:
        port: 3333
      app:
        elasticSearch:
          baseUrl: atl-prd-eas-01a.sec.ibm.com:9200,atl-prd-eas-01b.sec.ibm.com:9200,atl-prd-eas-01c.sec.ibm.com:9200
          indexName: servicenow
          type: problem
        serviceNow:
          scheme: https
          baseUrl: secsupportprd.service-now.com
          endpoint: "/api/x_ibmip_int_prb/ws/problem"
    env:
      LOG_FORMAT: plain
      LOG_LEVEL: DEBUG