---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: snow-update-listener
  namespace: xpp
  annotations:
    fluxcd.io/automated: "false"
    filter.fluxcd.io/chart-image: glob:*-master.*
spec:
  releaseName: snow-update-listener
  forceUpgrade: true
  chart:
    repository: https://na.artifactory.swg-devops.com/artifactory/mss-helm-virtual
    name: snow-update-listener
    version: 1.0.5-master
  values:
    service:
      targetPort: 3333
    readinessProbe:
      initialDelaySeconds: 30
    livenessProbe:
      initialDelaySeconds: 30
    image:
      repository: mss-docker.artifactory.swg-devops.com/snow-update-listener
      tag: 1.0.5-master.b6df3de8
    graphite:
      enabled: true
      host: atl-prd-statsnode-01a.sec.ibm.com
      prefix: prd.k8s.xpp
    secretName: snow-update-listener
    ingress:
      enabled: true
      hosts:
        - host: snow-update-listener.atl-prd.k8s.sec.ibm.com
          paths:
            - /
      tls:
        - hosts:
            - snow-update-listener.atl-prd.k8s.sec.ibm.com
          secretName: snow-update-listener
    config:
      server:
        port: 3333
      app:
        elasticSearch:
          baseUrl: atl-prd-eas-01a.sec.ibm.com:9200,atl-prd-eas-01b.sec.ibm.com:9200,atl-prd-eas-01c.sec.ibm.com:9200
          indexName: servicenow
          type: incident
        serviceNow:
          scheme: https
          baseUrl: secsupportprd.service-now.com
          endpoint: "/api/now/table/{schema}/{id}"
      spring:
        kafka:
          bootstrap-servers: atl-prd-kfk-01a.sec.ibm.com:9093,atl-prd-kfk-01b.sec.ibm.com:9093,atl-prd-kfk-01c.sec.ibm.com:9093
    env:
      LOG_FORMAT: plain
      LOG_LEVEL: DEBUG
