---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: ai-alert-external-siem-ids-ms
  namespace: xpp
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: glob:*-integration.*
spec:
  releaseName: ai-alert-external-siem-ids-ms
  forceUpgrade: false
  chart:
    repository: https://na.artifactory.swg-devops.com/artifactory/mss-helm-virtual
    name: ai-alert-external-siem-ids-ms
    version: 0.0.4-integration
  values:
    service:
      targetPort: 3333
    prometheusScrape:
      port: 3333
    readinessProbe:
      httpGet:
        port: 3333
    livenessProbe:
      httpGet:
        port: 3333
    replicaCount: 1
    revisionHistoryLimit: 1
    image:
      repository: mss-docker.artifactory.swg-devops.com/ai-alert-external-siem-ids-ms
      tag: 0.0.4-integration.5962317d
    graphite:
      enabled: true
      host: dal09-prd-statsnode-01a.sec.ibm.com
      prefix: dev.k8s.integration
    route:
      enabled: false
    ingress:
      enabled: true
      hosts:
      - host: ai-alert-external-siem-ids-ms-integration.dal09-dev.k8s-lab.sec.ibm.com
        paths:
        - /
      tls:
      - hosts:
        - ai-alert-external-siem-ids-ms-integration.dal09-dev.k8s-lab.sec.ibm.com
    config:
      app:
        ai-datasource:
          jdbc-url: jdbc:mysql://dal09-dev-aidb-01.sec.ibm.com:3306/ai
    env:
      DOCKER_REGISTRY_PULL_SECRET_NAME: docker-registry-pull
      LOG_FORMAT: json
      LOG_LEVEL: DEBUG
