---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: core-test-java-3
  namespace: xpp
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: glob:*-master.*
spec:
  releaseName: core-test-java-3
  forceUpgrade: true
  chart:
    repository: https://na.artifactory.swg-devops.com/artifactory/mss-helm-virtual
    name: core-test-java-3
    version: 0.0.3
  values:
    image:
      repository: mss-docker.artifactory.swg-devops.com/core-test-java-3
      tag: 0.0.3-master.64fa12b6
    imagePullSecrets:
    - name: xpp-docker-registry-pull
    graphite:
      enabled: false
      host: dal09-prd-statsnode-01a.sec.ibm.com
      prefix: dev.ocp.xpp
    # TEMPLATE: Insert other required configuration values here
