---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: device-mysql
  namespace: xpp
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: glob:*-master.*
spec:
  releaseName: device-mysql
  forceUpgrade: true
  chart:
    repository: https://na.artifactory.swg-devops.com/artifactory/mss-helm-virtual
    name: device-mysql
    version: 0.0.1-master
  values:
    service:
      targetPort: 3333
    readinessProbe:
      initialDelaySeconds: 60
    livenessProbe:
      initialDelaySeconds: 60
    image:
      repository: mss-docker.artifactory.swg-devops.com/device-mysql
      tag: 0.0.1-master.6d8fc18b
    graphite:
      enabled: true
      host: dal09-prd-statsnode-01a.sec.ibm.com
      prefix: dev.k8s.integration
    ingress:
      enabled: true
      hosts:
        - host: device-mysql-integration.dal09-dev.k8s-lab.sec.ibm.com
          paths:
            - /
    tls:
      - hosts:
          - device-mysql-integration.dal09-dev.k8s-lab.sec.ibm.com
    config:
      server:
        port: 3333
