---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: device-policy-ms
  namespace: xpp
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: glob:*-integration.*
spec:
  releaseName: device-policy-ms
  forceUpgrade: true
  chart:
    repository: https://na.artifactory.swg-devops.com/artifactory/mss-helm-virtual
    name: device-policy-ms
    version: 0.0.2-integration
  values:
    service:
      targetPort: 3333
    readinessProbe:
      initialDelaySeconds: 60
    livenessProbe:
      initialDelaySeconds: 60
    image:
      repository: mss-docker.artifactory.swg-devops.com/device-policy-ms
      tag: 0.0.2-integration.3d5d21ff
    graphite:
      enabled: true
      host: dal09-prd-statsnode-01a.sec.ibm.com
      prefix: dev.k8s.integration
    ingress:
      enabled: true
      hosts:
      - host: device-policy-ms-xpp.dal09-dev.k8s-lab.sec.ibm.com
        paths:
        - /
      tls:
      - hosts:
        - device-policy-ms-xpp.dal09-dev.k8s-lab.sec.ibm.com
    config:
      server:
        port: 3333
    env:
      LOG_FORMAT: plain
      LOG_LEVEL: DEBUG
