---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: email-jobs-daily
  namespace: xpp
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: glob:*-container.*
spec:

  releaseName: email-jobs-daily
  forceUpgrade: true
  chart:
    repository: https://na.artifactory.swg-devops.com/artifactory/mss-helm-virtual
    name: email-jobs
    version: 1.0.21-container
  values:
    image:
      repository: mss-docker.artifactory.swg-devops.com/email_jobs
      tag: 1.0.21-container.2ab9e9e0
    imagePullSecrets:
    - name: xpp-docker-registry-pull
    schedule: "20 7 * * *"
    args:
      arg1: -Denvironment=daily
      arg2: net.iss.mss.reporting.email.DailyManagedServiceEmailReportEmailHandler
    env:
      name: MSS_LOCAL_PROPS
      value: /appData/application.global.properties
    graphite:
      enabled: true
      host: dal09-prd-statsnode-01a.sec.ibm.com
      prefix: dev.ocp.xpp
