---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: glass-backend
  namespace: xpp
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: glob:*-develop.*
spec:
  releaseName: glass-backend-flux
  forceUpgrade: true
  chart:
    repository: https://na.artifactory.swg-devops.com/artifactory/mss-helm-virtual
    version: 1.0.13-develop
    name: glass-backend
  values:
    image:
      repository: mss-docker.artifactory.swg-devops.com/glass-backend
      tag: 1.0.28-develop.5f894cd7
    imagePullSecrets:
    - name: xpp-docker-registry-pull
    env:
      DOCKER_REGISTRY_PULL_SECRET_NAME: docker-registry-pull
      SERVICES_BASE_URL: https://dal09-dev-services.sec.ibm.com
      NODE_ENV: dev
      HOURS_BACK: 24
      LOG_FORMAT: plain
      LOG_LEVEL: info
      TOKEN_TYPE: SessionToken
      PILOT_AUTH_BLUEGROUP: glassgroup
      GLASS_CASE_MS_BASE_URL: https://glass-cases-ms-xpp.dal09-dev.k8s-lab.sec.ibm.com
    ingress:
      host: dal09-dev.k8s-lab.sec.ibm.com
