---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: tmx-web-ui
  namespace: xpp
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: glob:*-develop.*
spec:
  releaseName: tmx-web-ui
  forceUpgrade: true
  chart:
    repository: https://na.artifactory.swg-devops.com/artifactory/mss-helm-virtual
    version: 1.0.25-develop
    name: glass-webui
  values:
    image:
      repository: mss-docker.artifactory.swg-devops.com/glass-webui
      tag: 1.0.29-develop.36e08243
    imagePullSecrets:
    - name: xpp-docker-registry-pull
    env:
      DOCKER_REGISTRY_PULL_SECRET_NAME: docker-registry-pull
      SERVER: https://glass-backend-xpp.dal09-dev.k8s-lab.sec.ibm.com
      NEXTAUTH_URL: https://glass-webui-xpp.dal09-dev.k8s-lab.sec.ibm.com
      MSS_API: https://dal09-dev-services.sec.ibm.com
      LOG_FORMAT: plain
      LOG_LEVEL: info
    ingress:
      host: dal09-dev.k8s-lab.sec.ibm.com
      appDnsAlias: dal09-dev-console.sec.ibm.com
