---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: glass-cases-ms
  namespace: xpp
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: glob:*-develop.*
spec:
  releaseName: glass-cases-flux
  forceUpgrade: true
  chart:
    repository: https://na.artifactory.swg-devops.com/artifactory/mss-helm-virtual
    version: 1.0.3-rc
    name: glass-cases-ms
  values:
    image:
      repository: mss-docker.artifactory.swg-devops.com/glass-cases-ms
      tag: 1.0.7-rc.35-25dd0c45
    imagePullSecrets:
    - name: xpp-docker-registry-pull  
    env:
      DOCKER_REGISTRY_PULL_SECRET_NAME: docker-registry-pull
      MSS_API: https:/dal09-dev-services.sec.ibm.com
      LOG_FORMAT: plain
      LOG_LEVEL: info
      DB_POOL_MAX: 100
      PUBLIC_URL: https://glass-cases-ms-xpp.dal09-dev.k8s-lab.sec.ibm.com
    ingress:
      host: dal09-dev.k8s-lab.sec.ibm.com
