---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: mars-dome9-auditlogs-collector
  namespace: xpp
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: glob:*-master.*
spec:
  releaseName: mars-dome9-auditlogs-collector
  forceUpgrade: true
  chart:
    repository: https://na.artifactory.swg-devops.com/artifactory/mss-helm-virtual
    name: mars-dome9-auditlogs-collector
    version: 1.1.1-master
  values:
    replicaCount: 1
    revisionHistoryLimit: 1
    image:
      repository: mss-docker.artifactory.swg-devops.com/mars-dome9-auditlogs-collector
      tag: 1.1.1-master.4e51b39e
    secretName: mars-services
    imagePullSecrets:
    - name: docker-registry-pull
    graphite:
      enabled: false
      host: dal09-prd-statsnode-01a.sec.ibm.com
      prefix: dev.k8s.integration
    env:
      DOCKER_REGISTRY_PULL_SECRET_NAME: docker-registry-pull
      LOG_FORMAT: json
      LOG_LEVEL: DEBUG
      NEW_RELIC_LOG_FILE_NAME: STDOUT
      NEW_RELIC_LOG_LEVEL: INFO
      NEW_RELIC_SYNC_STARTUP: true
      NEW_RELIC_AGENT_ENABLED: true
      NEW_RELIC_SEND_DATA_ON_EXIT: true
      NEW_RELIC_SEND_DATA_ON_EXIT_THRESHOLD: 60
      NEW_RELIC_APP_NAME: mars-dome9-auditlogs-collector-dev
      NEW_RELIC_LABELS: Application:Mars-dome9-auditlogs-collector;Org:Lhs;Region:Dal09;Stack:Dev;Namespace:xpp
    config:
      app:
        services:
          baseUrl: https://dal09-dev-services.sec.ibm.com
          timeoutSeconds: 30
      spring:
        kafka:
          bootstrap-servers: dal09-dev-kfk-01a.sec.ibm.com:9093,dal09-dev-kfk-01b.sec.ibm.com:9093,dal09-dev-kfk-01c.sec.ibm.com:9093
