---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: mss-resilient-app-circuit-breaker-ms
  namespace: xpp
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: glob:*-integration.*
spec:
  releaseName: mss-resilient-app-circuit-breaker-ms
  forceUpgrade: true
  chart:
    repository: https://na.artifactory.swg-devops.com/artifactory/mss-helm-virtual
    name: mss-resilient-app-circuit-breaker-ms
    version: 0.0.14-integration
  values:
    replicaCount: 1
    revisionHistoryLimit: 1
    image:
      repository: mss-docker.artifactory.swg-devops.com/mss-resilient-app-circuit-breaker-ms
      tag: 0.0.19-integration.f9712d12
    graphite:
      enabled: true
      host: dal09-prd-statsnode-01a.sec.ibm.com
      prefix: dev.k8s.integration
    route:
      enabled: false
    ingress:
      enabled: true
      hosts:
      - host: mss-resilient-app-circuit-breaker-ms-integration.dal09-dev.k8s-lab.sec.ibm.com
        paths:
        - /
      tls:
      - hosts:
        - mss-resilient-app-circuit-breaker-ms-integration.dal09-dev.k8s-lab.sec.ibm.com
    imagePullSecrets:
    - name: docker-registry-pull
    env:
      DOCKER_REGISTRY_PULL_SECRET_NAME: docker-registry-pull
      LOG_FORMAT: json
      LOG_LEVEL: DEBUG
