---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: qradar-log-type-lookup-ms
  namespace: xpp
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: glob:*-integration.*
spec:
  releaseName: qradar-log-type-lookup-ms
  forceUpgrade: true
  chart:
    repository: https://na.artifactory.swg-devops.com/artifactory/mss-helm-virtual
    name: qradar-log-type-lookup-ms
    version: 1.0.6-integration
  values:
    log:
      level: DEBUG
    service:
      targetPort: 3333
    readinessProbe:
      initialDelaySeconds: 300
    livenessProbe:
      initialDelaySeconds: 300
    image:
      repository: mss-docker.artifactory.swg-devops.com/qradar-log-type-lookup-ms
      tag: 1.0.6-integration.ca28be04
    graphite:
      enabled: false
      host: dal09-prd-statsnode-01a.sec.ibm.com
      prefix: dev.k8s.integration
    secretsDir: "/vault/secrets"
    serviceAccount:
      create: true
    podAnnotations:
      vault.hashicorp.com/agent-inject: 'true'
      vault.hashicorp.com/role: 'qradar-log-type-lookup-ms'
      vault.hashicorp.com/agent-inject-secret-app.db.username: "secret/modules/qradar-log-type-lookup-ms/mss-datasource"
      vault.hashicorp.com/agent-inject-template-app.db.username: |-
        {{- with secret "secret/modules/qradar-log-type-lookup-ms/mss-datasource" -}}{{- .Data.data.USERNAME -}}{{- end }}
      vault.hashicorp.com/agent-inject-secret-app.db.password: "secret/modules/qradar-log-type-lookup-ms/mss-datasource"
      vault.hashicorp.com/agent-inject-template-app.db.password: |-
        {{- with secret "secret/modules/qradar-log-type-lookup-ms/mss-datasource" -}}{{- .Data.data.PASSWORD -}}{{- end }}
    ingress:
      enabled: true
      hosts:
      - host: qradar-log-type-lookup-ms-integration.dal09-dev.k8s-lab.sec.ibm.com
        paths:
        - /
      tls:
      - hosts:
        - qradar-log-type-lookup-ms-integration.dal09-dev.k8s-lab.sec.ibm.com
    config:
      server:
        port: 3333
      app:
        db:
          jdbc-url: jdbc:mysql://dal09-dev-mssdb-01a.sec.ibm.com:3306/mss
    env:
      LOG_FORMAT: plain
      LOG_LEVEL: DEBUG
