---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: soc-infrastruct-asset-tracking-ms
  namespace: xpp
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: glob:*-integration.*
spec:
  releaseName: soc-infrastruct-asset-tracking-ms
  forceUpgrade: true
  chart:
    repository: https://na.artifactory.swg-devops.com/artifactory/mss-helm-virtual
    name: soc-infrastruct-asset-tracking-ms
    version: 1.0.5-integration
  values:
    log:
      level: DEBUG
    service:
      targetPort: 3333
    readinessProbe:
      initialDelaySeconds: 120
    livenessProbe:
      initialDelaySeconds: 120
    image:
      repository: mss-docker.artifactory.swg-devops.com/soc-infrastruct-asset-tracking-ms
      tag: 1.0.5-integration.60d88842
    graphite:
      enabled: false
      host: dal09-prd-statsnode-01a.sec.ibm.com
      prefix: dev.k8s.integration
    secretsDir: "/vault/secrets"
    serviceAccount:
      create: true
    podAnnotations:
      vault.hashicorp.com/agent-inject: 'true'
      vault.hashicorp.com/role: 'soc-infrastruct-asset-tracking-ms'
      vault.hashicorp.com/agent-inject-secret-app.elastic-search.username: "secret/modules/soc-infrastruct-asset-tracking-ms/elastic-search"
      vault.hashicorp.com/agent-inject-template-app.elastic-search.username: |-
        {{- with secret "secret/modules/soc-infrastruct-asset-tracking-ms/elastic-search" -}}{{- .Data.data.ELASTICSEARCH_USERNAME -}}{{- end }}
      vault.hashicorp.com/agent-inject-secret-app.elastic-search.password: "secret/modules/soc-infrastruct-asset-tracking-ms/elastic-search"
      vault.hashicorp.com/agent-inject-template-app.elastic-search.password: |-
        {{- with secret "secret/modules/soc-infrastruct-asset-tracking-ms/elastic-search" -}}{{- .Data.data.ELASTICSEARCH_PASSWORD -}}{{- end }}
    ingress:
      enabled: true
      hosts:
      - host: soc-infrastruct-asset-tracking-ms-integration.dal09-dev.k8s-lab.sec.ibm.com
        paths:
        - /
      tls:
      - hosts:
        - soc-infrastruct-asset-tracking-ms-integration.dal09-dev.k8s-lab.sec.ibm.com
    config:
      server:
        port: 3333
      app:
        elasticSearch:
          baseUrl: dal09-dev-solr-01a.sec.ibm.com:9200,dal09-dev-solr-01b.sec.ibm.com:9200,dal09-dev-solr-01c.sec.ibm.com:9200
          indexName: socinfrastructassettracking
          type: infrastructassettracking
    env:
      LOG_FORMAT: plain
      LOG_LEVEL: DEBUG
