---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: xpsws-gateway
  namespace: xpp
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: glob:*-integration.*
spec:
  releaseName: xpsws-gateway
  forceUpgrade: true
  chart:
    repository: https://na.artifactory.swg-devops.com/artifactory/mss-helm-virtual
    name: xpsws-gateway
    version: 1.5.10-integration
  values:
    image:
      repository: mss-docker.artifactory.swg-devops.com/xpsws-gateway
      tag: 1.5.13-integration.2dd2acd3
    imagePullSecrets:
    - name: xpp-docker-registry-pull
    resources:
      limits:
        cpu: .5
      requests:
        cpu: .25
    graphite:
      enabled: false
      host: dal09-prd-statsnode-01a.sec.ibm.com
      prefix: dev.k8s.integration
    secretsDir: "/vault/secrets"
    serviceAccount:
      create: true
    podAnnotations:
      vault.hashicorp.com/agent-inject: 'true'
      vault.hashicorp.com/role: 'xpsws-gateway'
      vault.hashicorp.com/agent-inject-secret-app.elasticsearch.password: "secret/modules/xpsws-gateway/elasticsearch"
      vault.hashicorp.com/agent-inject-template-app.elasticsearch.password: |-
        {{- with secret "secret/modules/xpsws-gateway/elasticsearch" -}}{{- .Data.data.PASSWORD -}}{{- end }}
      vault.hashicorp.com/agent-inject-secret-app.elasticsearch.username: "secret/modules/xpsws-gateway/elasticsearch"
      vault.hashicorp.com/agent-inject-template-app.elasticsearch.username: |-
        {{- with secret "secret/modules/xpsws-gateway/elasticsearch" -}}{{- .Data.data.USERNAME -}}{{- end }}
      vault.hashicorp.com/agent-inject-secret-app.cm.token: "secret/modules/xpsws-gateway/cm-token"
      vault.hashicorp.com/agent-inject-template-app.cm.token: |-
        {{- with secret "secret/modules/xpsws-gateway/cm-token" -}}{{- .Data.data.TOKEN -}}{{- end }}
    route:
      enabled: false
    ingress:
      enabled: true
      hosts:
      - host: xpsws-gateway-integration.dal09-dev.k8s-lab.sec.ibm.com
        paths:
        - /
      tls:
      - hosts:
        - xpsws-gateway-integration.dal09-dev.k8s-lab.sec.ibm.com
    env:
      environment: dev
      es_urls: http://dal09-dev-solr-01a.sec.ibm.com:9200,http://dal09-dev-solr-01b.sec.ibm.com:9200,http://dal09-dev-solr-01c.sec.ibm.com:9200
      jwt_provider_url: https://jwt-provider-integration.dal09-dev.k8s-lab.sec.ibm.com
