---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: aura-credentials-ms
  namespace: xpp
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: glob:*-master.*
spec:
  releaseName: aura-credentials-ms
  forceUpgrade: true
  chart:
    repository: https://na.artifactory.swg-devops.com/artifactory/mss-helm-virtual
    name: aura-credentials-ms
    version: 0.0.5-master
  values:
    image:
      repository: mss-docker.artifactory.swg-devops.com/aura-credentials-ms
      tag: 0.0.5-master.43d325f3
    imagePullSecrets:
    - name: xpp-docker-registry-pull
    env:
      SPRING_PROFILES_ACTIVE: atl-stg
