---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: aura-migration-ms
  namespace: xpp
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: glob:*-master.*
spec:
  releaseName: aura-migration-ms
  forceUpgrade: true
  chart:
    repository: https://na.artifactory.swg-devops.com/artifactory/mss-helm-virtual
    name: aura-migration-ms
    version: 0.0.8-master
  values:
    image:
      repository: mss-docker.artifactory.swg-devops.com/aura-migration-ms
      tag: 0.0.8-master.87a498fe
    imagePullSecrets:
    - name: xpp-docker-registry-pull
    env:
      SPRING_PROFILES_ACTIVE: atl-stg
    graphite:
      enabled: false
      host: atl-prd-statsnode-01a.sec.ibm.com
      prefix: stg.ocp.xpp
    # TEMPLATE: Insert other required configuration values here
