---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: customer-contact-to-role-ms
  namespace: xpp
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: glob:*-openshift.*
spec:
  releaseName: customer-contact-to-role-ms
  forceUpgrade: true
  chart:
    repository: https://na.artifactory.swg-devops.com/artifactory/mss-helm-virtual
    name: customer-contact-to-role-ms
    version: 1.0.34-openshift
  values:
    image:
      repository: mss-docker.artifactory.swg-devops.com/customer-contact-to-role-ms
      tag: 1.0.34-openshift.edbc6549
    imagePullSecrets:
    - name: xpp-docker-registry-pull
    route:
      host: customer-contact-to-role-ms.apps-priv.atl-stg-ocp-01.cl.sec.ibm.com
    readinessProbe:
      initialDelaySeconds: 120
      periodSeconds: 20
    livenessProbe:
      initialDelaySeconds: 120
      periodSeconds: 20
    secretName: cm-token
    env:
      environment: stg
      #config.sektretfilepath=/etc/cm-token/cm.token
      #config.username=xpsms
      elastic_search_ms: https://es-search-ms.atl-stg.k8s.sec.ibm.com/es_search
      remedyUpdateMsUrl: https://es-search-ms.atl-stg.k8s.sec.ibm.com/remedy_update_ms
      system_only_fields: password,failedLoginCount,passPhrase
