---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: customer-ms
  namespace: xpp
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: glob:*-openshift.*
spec:
  releaseName: customer-ms
  forceUpgrade: true
  chart:
    repository: https://na.artifactory.swg-devops.com/artifactory/mss-helm-virtual
    name: customer-ms
    version: 1.1.13-openshift
  values:
    image:
      repository: mss-docker.artifactory.swg-devops.com/customer-ms
      tag: 1.1.13-openshift.0e12f585
    imagePullSecrets:
    - name: xpp-docker-registry-pull
    route:
      host: customer-ms.apps-priv.atl-stg-ocp-01.cl.sec.ibm.com
    env:
      vault_url: https://stg-vault.sec.ibm.com:8200
      vault_role_id:
      vault_secret_id:
      vault_path: secret/modules/customer_ms/
      elastic_search_ms: https://es-search-ms.apps-priv.atl-stg-ocp-01.cl.sec.ibm.com/es_search
      remedy_save_ms: https://stg-services.sec.ibm.com/micro/remedy_update_ms
      environment: stg
