---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: xforcevultomss-atl-stg-job
  namespace: xpp
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: glob:*-master.*
spec:
  releaseName: xforcevultomss-atl-stg-job
  forceUpgrade: true
  chart:
    repository: https://na.artifactory.swg-devops.com/artifactory/mss-helm-virtual
    name: databasereplication
    version: 1.3.1-master
  values:
    image:
      repository: mss-docker.artifactory.swg-devops.com/databasereplication
      tag: 1.3.1-master.f06c5b04
    imagePullSecrets:
    - name: xpp-docker-registry-pull
    schedule: "46 2,11,20 * * *"
    args:
      path: /opt/mssdev/DatabaseReplication/bin/XforceVulnerabilityToMssReplication.sh
      cmd: run
    env:
      name: STACK
      value: stg