---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: device-login-ms
  namespace: xpp
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: glob:*-openshift.*
spec:
  releaseName: device-login-ms
  forceUpgrade: true
  chart:
    repository: https://na.artifactory.swg-devops.com/artifactory/mss-helm-virtual
    name: device-login-ms
    version: 1.0.37-openshift
  values:
    image:
      repository: mss-docker.artifactory.swg-devops.com/device-login-ms
      tag: 1.0.37-openshift.8cee3250
    imagePullSecrets:
    - name: xpp-docker-registry-pull    
    env:
      ENV: stg
