---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: ecd-file-parser
  namespace: xpp
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: glob:*-master.*
spec:
  releaseName: ecd-file-parser
  forceUpgrade: true
  chart:
    repository: https://na.artifactory.swg-devops.com/artifactory/mss-helm-virtual
    name: ecd-file-parser
    version: 0.0.5-master
  values:
    log:
      format: plain
    image:
      repository: mss-docker.artifactory.swg-devops.com/ecd-file-parser
      tag: 0.0.5-master.6919b6a5
    imagePullSecrets:
    - name: xpp-docker-registry-pull
    resources:
      limits:
        cpu: 2
      requests:
        cpu: 1
    graphite:
      enabled: true
      host: atl-prd-statsnode-01a.sec.ibm.com
      prefix: stg.ocp.xpp
    # TEMPLATE: Insert other required configuration values here
    config:
      spring:
        #profiles: dal09-dev
        datasource:
          url: "jdbc:db2://02a3be17-3906-4e5a-98e4-33120532a590.bu6tc4nd0urletsa6ufg.databases.appdomain.cloud:32054/BLUDB:currentSchema=PROD;sslConnection=true;"
        kafka:
          bootstrap-servers: atl-stg-kfk-01a.sec.ibm.com:9093,atl-stg-kfk-01b.sec.ibm.com:9093,atl-stg-kfk-01c.sec.ibm.com:9093
      ecd:
        stack:
          env: atl-stg
        esJson:
          microserviceBaseUrl: https://stg-services.sec.ibm.com
          timeoutSeconds: 30
      fileProcessStateIndex:
        retryAttempts: 1
        retryBackoffSeconds: 3
      box:
        client:
          maxCacheEntries: 5
    env:
      NEW_RELIC_APP_NAME: ecd-file-parser-atl-stg
      NEW_RELIC_PROCESS_HOST_DISPLAY_NAME: ecd-atl-stg
      NEW_RELIC_AGENT_ENABLED: true
      NEW_RELIC_LOG_LEVEL: warn
      NEW_RELIC_LOG_FILE_NAME: STDOUT
      NEW_RELIC_SYNC_STARTUP: true
      NEW_RELIC_SEND_DATA_ON_EXIT: true
      NEW_RELIC_SEND_DATA_ON_EXIT_THRESHOLD: 6
      KAFKA_SSL_TRUSTSTORE_LOCATION: /opt/app/secrets.d/dev_kafka.truststore.jks
      KAFKA_SSL_KEYSTORE_LOCATION: /opt/app/secrets.d/dev_kafka.client_keystore.jks
