---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: ecd-process-failed-scheduler
  namespace: xpp
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: glob:*-master.*
spec:
  releaseName: ecd-process-failed-scheduler
  forceUpgrade: true
  chart:
    repository: https://na.artifactory.swg-devops.com/artifactory/mss-helm-virtual
    name: ecd-process-failed-scheduler
    version: 2.0.0-master
  values:
    image:
      repository: mss-docker.artifactory.swg-devops.com/ecd-process-failed-scheduler
      tag: 3.0.0-master.f439a10e
    imagePullSecrets:
    - name: xpp-docker-registry-pull
    resources:
      limits:
        cpu: 1
      requests:
        cpu: .25
    graphite:
      enabled: true
      host: atl-prd-statsnode-01a.sec.ibm.com
      prefix: stg.ocp.xpp
    # TEMPLATE: Insert other required configuration values here
    config:
      spring:
        datasource:
          url: "jdbc:db2://atl-prd-bkt-01a.mss.iss.net:50000/mydb:currentSchema=TEST;"
        kafka:
          bootstrap-servers: atl-stg-kfk-01a.sec.ibm.com:9093,atl-stg-kfk-01b.sec.ibm.com:9093,atl-stg-kfk-01c.sec.ibm.com:9093
      ecd:
        stack:
          env: atl-stg
        esJson:
          microserviceBaseUrl: https://stg-services.sec.ibm.com
          timeoutSeconds: 30
      fileProcessStateIndex:
        retryAttempts: 1
        retryBackoffSeconds: 3
      box:
        client:
          maxCacheEntries: 5
    env:
      NEW_RELIC_APP_NAME: ecd-process-failed-scheduler-dal09-dev
      NEW_RELIC_PROCESS_HOST_DISPLAY_NAME: ecd-atl-stg
      NEW_RELIC_AGENT_ENABLED: false
      NEW_RELIC_LOG_LEVEL: warn
      NEW_RELIC_LOG_FILE_NAME: STDOUT
      NEW_RELIC_SYNC_STARTUP: true
      NEW_RELIC_SEND_DATA_ON_EXIT: true
      NEW_RELIC_SEND_DATA_ON_EXIT_THRESHOLD: 6
      KAFKA_SSL_TRUSTSTORE_LOCATION: /opt/app/secrets.d/dev_kafka.truststore.jks
      KAFKA_SSL_KEYSTORE_LOCATION: /opt/app/secrets.d/dev_kafka.client_keystore.jks
