---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: es-json-ms-stg
  namespace: xpp
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: glob:*-openshift.*
spec:
  releaseName: es-json-ms-stg
  forceUpgrade: true
  chart:
    repository: https://na.artifactory.swg-devops.com/artifactory/mss-helm-virtual
    name: es-json-ms
    version: 1.0.4-openshift
  values:
    image:
      repository: mss-docker.artifactory.swg-devops.com/es-json-ms
      tag: 1.0.13-openshift.bdb4dea4
    imagePullSecrets:
    - name: xpp-docker-registry-pull
    env:
      env: stg
      environment: stg
      elastic_search_hosts: https://atl-stg-esmasdata-02a.sec.ibm.com:9200,https://atl-stg-esmasdata-02b.sec.ibm.com:9200,https://atl-stg-esmasdata-02c.sec.ibm.com:9200
      vault_url: https://stg-vault.sec.ibm.com:8200
      vault_role_id: 237e74e5-4c8e-70a1-9bcf-02990e43290f
      vault_secret_id: cbe63578-563c-1aaf-8fb3-3a0bbcabf11b
      vault_path: secret/modules/es_json_ms/
