---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: remedy-metadata-ms
  namespace: xpp
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: glob:*-openshift.*
spec:
  releaseName: remedy-metadata-ms
  forceUpgrade: true
  chart:
    repository: https://na.artifactory.swg-devops.com/artifactory/mss-helm-virtual
    name: remedy-metadata-ms
    version: 1.0.1-openshift
  values:
    image:
      repository: mss-docker.artifactory.swg-devops.com/remedy-metadata-ms
      tag: 1.0.1-openshift.48c4e125
    imagePullSecrets:
    - name: xpp-docker-registry-pull
    secretDir: /etc/cm.token
    secretName: cm-token
    env:
      environment: stg
      permissionsengine_es_cluster_name: xps-atl-stg
