---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: seat-configuration-ms
  namespace: xpp
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: glob:*-master.*
spec:
  releaseName: seat-configuration-ms
  forceUpgrade: false
  chart:
    repository: https://na.artifactory.swg-devops.com/artifactory/mss-helm-virtual
    name: seat-configuration-ms
    version: 0.1.9-master
  values:
    image:
      repository: mss-docker.artifactory.swg-devops.com/seat-configuration-ms
      tag: 0.1.9-master.b7d7ce0a
    imagePullSecrets:
    - name: xpp-docker-registry-pull
    graphite:
      enabled: false
      host: atl-prd-statsnode-01a.sec.ibm.com
      prefix: stg.ocp.xpp
    # TEMPLATE: Insert other required configuration values here
