---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: secure-proxy-ms
  namespace: xpp
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: glob:*-openshift.*
spec:
  releaseName: secure-proxy-ms
  forceUpgrade: true
  chart:
    repository: https://na.artifactory.swg-devops.com/artifactory/mss-helm-virtual
    name: secure-proxy-ms
    version: 1.1.15-openshift
  values:
    image:
      repository: mss-docker.artifactory.swg-devops.com/secure-proxy-ms
      tag: 1.1.15-openshift.1b792d99
    imagePullSecrets:
    - name: xpp-docker-registry-pull
    route:
      host: secure-proxy-ms.apps-priv.atl-stg-ocp-01.cl.sec.ibm.com
    env:
      customer_data_permissions_ms: https://customer-data-permissions-ms.apps-priv.atl-stg-ocp-01.cl.sec.ibm.com/customer_data_permissions
