---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: slack-data-pull-stg-ocp-01
  namespace: xpp
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: glob:*-container.*
spec:
  releaseName: slack-data-pull-stg-ocp-01
  forceUpgrade: true
  chart:
    repository: https://na.artifactory.swg-devops.com/artifactory/mss-helm-virtual
    name: slack-data-pull
    version: 0.0.2-container
  values:
    image:
      repository: mss-docker.artifactory.swg-devops.com/slack-data-pull
      tag: 0.0.2-container.07ed9351
    imagePullSecrets:
    - name: xpp-docker-registry-pull
    graphite:
      enabled: false
      host: dal09-prd-statsnode-01a.sec.ibm.com
      prefix: dev.ocp.xpp
    # TEMPLATE: Insert other required configuration values
