---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: snow-update-listener
  namespace: xpp
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: glob:*-xps72720.*
spec:
  releaseName: snow-update-listener
  forceUpgrade: true
  chart:
    repository: https://na.artifactory.swg-devops.com/artifactory/mss-helm-virtual
    name: snow-update-listener
    version: 1.0.7-xps94542
  values:
    service:
      targetPort: 3333
    readinessProbe:
      initialDelaySeconds: 30
    livenessProbe:
      initialDelaySeconds: 30
    image:
      repository: mss-docker.artifactory.swg-devops.com/snow-update-listener
      tag: 1.0.7-xps72720.05b33ada
    graphite:
      enabled: true
      host: atl-prd-statsnode-01a.sec.ibm.com
      prefix: stg.ocp.xpp
    secretName: snow-update-listener
    ingress:
      enabled: false
    route:
      enabled: true
      host: snow-update-listener-ms.apps-priv.atl-stg-ocp-01.cl.sec.ibm.com
    config:
      server:
        port: 3333
      app:
        elasticSearch:
          baseUrl: atl-stg-esmasdata-02a.sec.ibm.com:9200,atl-stg-esmasdata-02b.sec.ibm.com:9200,atl-stg-esmasdata-02c.sec.ibm.com:9200
        serviceNow:
          scheme: https
          baseUrl: secsupportstg.service-now.com
          endpoint: "/api/now/table/{schema}/{id}"
      spring:
        kafka:
          bootstrap-servers: atl-stg-kfk-01a.sec.ibm.com:9093,atl-stg-kfk-01b.sec.ibm.com:9093,atl-stg-kfk-01c.sec.ibm.com:9093
    env:
      LOG_FORMAT: plain
      LOG_LEVEL: DEBUG
