---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: tdi-analytics-siem
  namespace: xpp
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: glob:*-ctgit0001.*
spec:
  releaseName: tdi-analytics-siem
  forceUpgrade: true
  chart:
    repository: https://na.artifactory.swg-devops.com/artifactory/mss-helm-virtual
    name: tdi-analytics-siem
    version: 0.1.1
  values:
    image:
      repository: mss-docker.artifactory.swg-devops.com/tdi-analytics-siem
      tag: 0.1.1-ctgit0001.d1022b85
    resources:
      limits:
        cpu: 2
      requests:
        cpu: 1
    imagePullSecrets:
    - name: xpp-docker-registry-pull
    graphite:
      enabled: false
      host: atl-prd-statsnode-01a.sec.ibm.com
      prefix: stg.ocp.xpp
    # TEMPLATE: Insert other required configuration values here
