---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: ticket-detail-ms
  namespace: xpp
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: glob:*-openshift.*
spec:
  releaseName: ticket-detail-ms
  forceUpgrade: true
  chart:
    repository: https://na.artifactory.swg-devops.com/artifactory/mss-helm-virtual
    name: ticket-detail-ms
    version: 1.4.2-openshift
  values:
    image:
      repository: mss-docker.artifactory.swg-devops.com/ticket-detail-ms
      tag: 1.4.2-openshift.6efb3889
    imagePullSecrets:
    - name: xpp-docker-registry-pull
    env:
      environment: stg
      processor.threadCount: 5
      dataPermServiceUrl: https://customer-data-permissions-ms.atl-stg.k8s.sec.ibm.com/customer_data_permissions
      elasticSearchMsUrl: https://es-search-ms.atl-stg.k8s.sec.ibm.com/es_search
      remedyUpdateMsUrl: https://remedy-update-ms.atl-stg.k8s.sec.ibm.com/remedy_update_ms
      userMsUrl: https://user-ms.atl-stg.k8s.sec.ibm.com/user
      ticketDeviceMapperUrl: https://ticket-device-mapping-ms.atl-stg.k8s.sec.ibm.com/ticket_device_mapping/
