---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: glass-backend
  namespace: master
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: glob:*-develop.*
spec:
  releaseName: glass-backend-flux
  forceUpgrade: true
  chart:
    repository: https://na.artifactory.swg-devops.com/artifactory/mss-helm-virtual
    version: 1.0.26-develop
    name: glass-backend
  values:
    image:
      repository: mss-docker.artifactory.swg-devops.com/glass-backend
      tag: 1.0.28-develop.5f894cd7
    imagePullSecrets:
    - name: xpp-docker-registry-pull
    env:
      DOCKER_REGISTRY_PULL_SECRET_NAME: docker-registry-pull
      SERVICES_BASE_URL: https://stg-services.sec.ibm.com
      NODE_ENV: stage
      HOURS_BACK: 24
      TOKEN_TYPE: SessionToken
      GLASS_CASE_MS_BASE_URL: http://glass-cases-ms.master:8080
      WTDS_SERVICE_URL: http://atl-stg-lmsrp-01a.sec.ibm.com:8000
    ingress:
      host: atl-stg.k8s.sec.ibm.com
